// Auto-generated emoji data (1790 entries)
pub const Emoji = struct {
    glyph: [:0]const u8,
    name: [:0]const u8,
};

pub const emoji_list = [_]Emoji{
    .{ .glyph = "😀", .name = "grinning face" },
    .{ .glyph = "😃", .name = "grinning face with big eyes" },
    .{ .glyph = "😄", .name = "grinning face with smiling eyes" },
    .{ .glyph = "😁", .name = "beaming face with smiling eyes" },
    .{ .glyph = "😆", .name = "grinning squinting face" },
    .{ .glyph = "😅", .name = "grinning face with sweat" },
    .{ .glyph = "🤣", .name = "rolling on the floor laughing" },
    .{ .glyph = "😂", .name = "face with tears of joy" },
    .{ .glyph = "🙂", .name = "slightly smiling face" },
    .{ .glyph = "🙃", .name = "upside-down face" },
    .{ .glyph = "🫠", .name = "melting face" },
    .{ .glyph = "😉", .name = "winking face" },
    .{ .glyph = "😊", .name = "smiling face with smiling eyes" },
    .{ .glyph = "😇", .name = "smiling face with halo" },
    .{ .glyph = "🥰", .name = "smiling face with hearts" },
    .{ .glyph = "😍", .name = "smiling face with heart-eyes" },
    .{ .glyph = "🤩", .name = "star-struck" },
    .{ .glyph = "😘", .name = "face blowing a kiss" },
    .{ .glyph = "😗", .name = "kissing face" },
    .{ .glyph = "😚", .name = "kissing face with closed eyes" },
    .{ .glyph = "😙", .name = "kissing face with smiling eyes" },
    .{ .glyph = "🥲", .name = "smiling face with tear" },
    .{ .glyph = "😋", .name = "face savoring food" },
    .{ .glyph = "😛", .name = "face with tongue" },
    .{ .glyph = "😜", .name = "winking face with tongue" },
    .{ .glyph = "🤪", .name = "zany face" },
    .{ .glyph = "😝", .name = "squinting face with tongue" },
    .{ .glyph = "🤑", .name = "money-mouth face" },
    .{ .glyph = "🤗", .name = "smiling face with open hands" },
    .{ .glyph = "🤭", .name = "face with hand over mouth" },
    .{ .glyph = "🫢", .name = "face with open eyes and hand over mouth" },
    .{ .glyph = "🫣", .name = "face with peeking eye" },
    .{ .glyph = "🤫", .name = "shushing face" },
    .{ .glyph = "🤔", .name = "thinking face" },
    .{ .glyph = "🫡", .name = "saluting face" },
    .{ .glyph = "🤐", .name = "zipper-mouth face" },
    .{ .glyph = "🤨", .name = "face with raised eyebrow" },
    .{ .glyph = "😐", .name = "neutral face" },
    .{ .glyph = "😑", .name = "expressionless face" },
    .{ .glyph = "😶", .name = "face without mouth" },
    .{ .glyph = "🫥", .name = "dotted line face" },
    .{ .glyph = "😶‍🌫", .name = "face in clouds" },
    .{ .glyph = "😏", .name = "smirking face" },
    .{ .glyph = "😒", .name = "unamused face" },
    .{ .glyph = "🙄", .name = "face with rolling eyes" },
    .{ .glyph = "😬", .name = "grimacing face" },
    .{ .glyph = "😮‍💨", .name = "face exhaling" },
    .{ .glyph = "🤥", .name = "lying face" },
    .{ .glyph = "🫨", .name = "shaking face" },
    .{ .glyph = "🙂‍↔", .name = "head shaking horizontally" },
    .{ .glyph = "🙂‍↕", .name = "head shaking vertically" },
    .{ .glyph = "😌", .name = "relieved face" },
    .{ .glyph = "😔", .name = "pensive face" },
    .{ .glyph = "😪", .name = "sleepy face" },
    .{ .glyph = "🤤", .name = "drooling face" },
    .{ .glyph = "😴", .name = "sleeping face" },
    .{ .glyph = "😷", .name = "face with medical mask" },
    .{ .glyph = "🤒", .name = "face with thermometer" },
    .{ .glyph = "🤕", .name = "face with head-bandage" },
    .{ .glyph = "🤢", .name = "nauseated face" },
    .{ .glyph = "🤮", .name = "face vomiting" },
    .{ .glyph = "🤧", .name = "sneezing face" },
    .{ .glyph = "🥵", .name = "hot face" },
    .{ .glyph = "🥶", .name = "cold face" },
    .{ .glyph = "🥴", .name = "woozy face" },
    .{ .glyph = "😵", .name = "face with crossed-out eyes" },
    .{ .glyph = "😵‍💫", .name = "face with spiral eyes" },
    .{ .glyph = "🤯", .name = "exploding head" },
    .{ .glyph = "🤠", .name = "cowboy hat face" },
    .{ .glyph = "🥳", .name = "partying face" },
    .{ .glyph = "🥸", .name = "disguised face" },
    .{ .glyph = "😎", .name = "smiling face with sunglasses" },
    .{ .glyph = "🤓", .name = "nerd face" },
    .{ .glyph = "🧐", .name = "face with monocle" },
    .{ .glyph = "😕", .name = "confused face" },
    .{ .glyph = "🫤", .name = "face with diagonal mouth" },
    .{ .glyph = "😟", .name = "worried face" },
    .{ .glyph = "🙁", .name = "slightly frowning face" },
    .{ .glyph = "😮", .name = "face with open mouth" },
    .{ .glyph = "😯", .name = "hushed face" },
    .{ .glyph = "😲", .name = "astonished face" },
    .{ .glyph = "😳", .name = "flushed face" },
    .{ .glyph = "🥺", .name = "pleading face" },
    .{ .glyph = "🥹", .name = "face holding back tears" },
    .{ .glyph = "😦", .name = "frowning face with open mouth" },
    .{ .glyph = "😧", .name = "anguished face" },
    .{ .glyph = "😨", .name = "fearful face" },
    .{ .glyph = "😰", .name = "anxious face with sweat" },
    .{ .glyph = "😥", .name = "sad but relieved face" },
    .{ .glyph = "😢", .name = "crying face" },
    .{ .glyph = "😭", .name = "loudly crying face" },
    .{ .glyph = "😱", .name = "face screaming in fear" },
    .{ .glyph = "😖", .name = "confounded face" },
    .{ .glyph = "😣", .name = "persevering face" },
    .{ .glyph = "😞", .name = "disappointed face" },
    .{ .glyph = "😓", .name = "downcast face with sweat" },
    .{ .glyph = "😩", .name = "weary face" },
    .{ .glyph = "😫", .name = "tired face" },
    .{ .glyph = "🥱", .name = "yawning face" },
    .{ .glyph = "😤", .name = "face with steam from nose" },
    .{ .glyph = "😡", .name = "enraged face" },
    .{ .glyph = "😠", .name = "angry face" },
    .{ .glyph = "🤬", .name = "face with symbols on mouth" },
    .{ .glyph = "😈", .name = "smiling face with horns" },
    .{ .glyph = "👿", .name = "angry face with horns" },
    .{ .glyph = "💀", .name = "skull" },
    .{ .glyph = "💩", .name = "pile of poo" },
    .{ .glyph = "🤡", .name = "clown face" },
    .{ .glyph = "👹", .name = "ogre" },
    .{ .glyph = "👺", .name = "goblin" },
    .{ .glyph = "👻", .name = "ghost" },
    .{ .glyph = "👽", .name = "alien" },
    .{ .glyph = "👾", .name = "alien monster" },
    .{ .glyph = "🤖", .name = "robot" },
    .{ .glyph = "😺", .name = "grinning cat" },
    .{ .glyph = "😸", .name = "grinning cat with smiling eyes" },
    .{ .glyph = "😹", .name = "cat with tears of joy" },
    .{ .glyph = "😻", .name = "smiling cat with heart-eyes" },
    .{ .glyph = "😼", .name = "cat with wry smile" },
    .{ .glyph = "😽", .name = "kissing cat" },
    .{ .glyph = "🙀", .name = "weary cat" },
    .{ .glyph = "😿", .name = "crying cat" },
    .{ .glyph = "😾", .name = "pouting cat" },
    .{ .glyph = "🙈", .name = "see-no-evil monkey" },
    .{ .glyph = "🙉", .name = "hear-no-evil monkey" },
    .{ .glyph = "🙊", .name = "speak-no-evil monkey" },
    .{ .glyph = "💌", .name = "love letter" },
    .{ .glyph = "💘", .name = "heart with arrow" },
    .{ .glyph = "💝", .name = "heart with ribbon" },
    .{ .glyph = "💖", .name = "sparkling heart" },
    .{ .glyph = "💗", .name = "growing heart" },
    .{ .glyph = "💓", .name = "beating heart" },
    .{ .glyph = "💞", .name = "revolving hearts" },
    .{ .glyph = "💕", .name = "two hearts" },
    .{ .glyph = "💟", .name = "heart decoration" },
    .{ .glyph = "💔", .name = "broken heart" },
    .{ .glyph = "🩷", .name = "pink heart" },
    .{ .glyph = "🧡", .name = "orange heart" },
    .{ .glyph = "💛", .name = "yellow heart" },
    .{ .glyph = "💚", .name = "green heart" },
    .{ .glyph = "💙", .name = "blue heart" },
    .{ .glyph = "🩵", .name = "light blue heart" },
    .{ .glyph = "💜", .name = "purple heart" },
    .{ .glyph = "🤎", .name = "brown heart" },
    .{ .glyph = "🖤", .name = "black heart" },
    .{ .glyph = "🩶", .name = "grey heart" },
    .{ .glyph = "🤍", .name = "white heart" },
    .{ .glyph = "💋", .name = "kiss mark" },
    .{ .glyph = "💯", .name = "hundred points" },
    .{ .glyph = "💢", .name = "anger symbol" },
    .{ .glyph = "💥", .name = "collision" },
    .{ .glyph = "💫", .name = "dizzy" },
    .{ .glyph = "💦", .name = "sweat droplets" },
    .{ .glyph = "💨", .name = "dashing away" },
    .{ .glyph = "🕳", .name = "hole" },
    .{ .glyph = "💬", .name = "speech balloon" },
    .{ .glyph = "👁‍🗨", .name = "eye in speech bubble" },
    .{ .glyph = "🗨", .name = "left speech bubble" },
    .{ .glyph = "🗯", .name = "right anger bubble" },
    .{ .glyph = "💭", .name = "thought balloon" },
    .{ .glyph = "💤", .name = "ZZZ" },
    .{ .glyph = "👋", .name = "waving hand" },
    .{ .glyph = "🤚", .name = "raised back of hand" },
    .{ .glyph = "🖐", .name = "hand with fingers splayed" },
    .{ .glyph = "🖖", .name = "vulcan salute" },
    .{ .glyph = "🫱", .name = "rightwards hand" },
    .{ .glyph = "🫲", .name = "leftwards hand" },
    .{ .glyph = "🫳", .name = "palm down hand" },
    .{ .glyph = "🫴", .name = "palm up hand" },
    .{ .glyph = "🫷", .name = "leftwards pushing hand" },
    .{ .glyph = "🫸", .name = "rightwards pushing hand" },
    .{ .glyph = "👌", .name = "OK hand" },
    .{ .glyph = "🤌", .name = "pinched fingers" },
    .{ .glyph = "🤏", .name = "pinching hand" },
    .{ .glyph = "🤞", .name = "crossed fingers" },
    .{ .glyph = "🫰", .name = "hand with index finger and thumb crossed" },
    .{ .glyph = "🤟", .name = "love-you gesture" },
    .{ .glyph = "🤘", .name = "sign of the horns" },
    .{ .glyph = "🤙", .name = "call me hand" },
    .{ .glyph = "👈", .name = "backhand index pointing left" },
    .{ .glyph = "👉", .name = "backhand index pointing right" },
    .{ .glyph = "👆", .name = "backhand index pointing up" },
    .{ .glyph = "🖕", .name = "middle finger" },
    .{ .glyph = "👇", .name = "backhand index pointing down" },
    .{ .glyph = "🫵", .name = "index pointing at the viewer" },
    .{ .glyph = "👍", .name = "thumbs up" },
    .{ .glyph = "👎", .name = "thumbs down" },
    .{ .glyph = "👊", .name = "oncoming fist" },
    .{ .glyph = "🤛", .name = "left-facing fist" },
    .{ .glyph = "🤜", .name = "right-facing fist" },
    .{ .glyph = "👏", .name = "clapping hands" },
    .{ .glyph = "🙌", .name = "raising hands" },
    .{ .glyph = "🫶", .name = "heart hands" },
    .{ .glyph = "👐", .name = "open hands" },
    .{ .glyph = "🤲", .name = "palms up together" },
    .{ .glyph = "🤝", .name = "handshake" },
    .{ .glyph = "🙏", .name = "folded hands" },
    .{ .glyph = "💅", .name = "nail polish" },
    .{ .glyph = "🤳", .name = "selfie" },
    .{ .glyph = "💪", .name = "flexed biceps" },
    .{ .glyph = "🦾", .name = "mechanical arm" },
    .{ .glyph = "🦿", .name = "mechanical leg" },
    .{ .glyph = "🦵", .name = "leg" },
    .{ .glyph = "🦶", .name = "foot" },
    .{ .glyph = "👂", .name = "ear" },
    .{ .glyph = "🦻", .name = "ear with hearing aid" },
    .{ .glyph = "👃", .name = "nose" },
    .{ .glyph = "🧠", .name = "brain" },
    .{ .glyph = "🫀", .name = "anatomical heart" },
    .{ .glyph = "🫁", .name = "lungs" },
    .{ .glyph = "🦷", .name = "tooth" },
    .{ .glyph = "🦴", .name = "bone" },
    .{ .glyph = "👀", .name = "eyes" },
    .{ .glyph = "👁", .name = "eye" },
    .{ .glyph = "👅", .name = "tongue" },
    .{ .glyph = "👄", .name = "mouth" },
    .{ .glyph = "🫦", .name = "biting lip" },
    .{ .glyph = "👶", .name = "baby" },
    .{ .glyph = "🧒", .name = "child" },
    .{ .glyph = "👦", .name = "boy" },
    .{ .glyph = "👧", .name = "girl" },
    .{ .glyph = "🧑", .name = "person" },
    .{ .glyph = "👱", .name = "person blond hair" },
    .{ .glyph = "👨", .name = "man" },
    .{ .glyph = "🧔", .name = "person beard" },
    .{ .glyph = "🧔‍♂", .name = "man beard" },
    .{ .glyph = "👱‍♂", .name = "man blond hair" },
    .{ .glyph = "👩", .name = "woman" },
    .{ .glyph = "🧔‍♀", .name = "woman beard" },
    .{ .glyph = "👱‍♀", .name = "woman blond hair" },
    .{ .glyph = "🧓", .name = "older person" },
    .{ .glyph = "👴", .name = "old man" },
    .{ .glyph = "👵", .name = "old woman" },
    .{ .glyph = "🙍", .name = "person frowning" },
    .{ .glyph = "🙍‍♂", .name = "man frowning" },
    .{ .glyph = "🙍‍♀", .name = "woman frowning" },
    .{ .glyph = "🙎", .name = "person pouting" },
    .{ .glyph = "🙎‍♂", .name = "man pouting" },
    .{ .glyph = "🙎‍♀", .name = "woman pouting" },
    .{ .glyph = "🙅", .name = "person gesturing NO" },
    .{ .glyph = "🙅‍♂", .name = "man gesturing NO" },
    .{ .glyph = "🙅‍♀", .name = "woman gesturing NO" },
    .{ .glyph = "🙆", .name = "person gesturing OK" },
    .{ .glyph = "🙆‍♂", .name = "man gesturing OK" },
    .{ .glyph = "🙆‍♀", .name = "woman gesturing OK" },
    .{ .glyph = "💁", .name = "person tipping hand" },
    .{ .glyph = "💁‍♂", .name = "man tipping hand" },
    .{ .glyph = "💁‍♀", .name = "woman tipping hand" },
    .{ .glyph = "🙋", .name = "person raising hand" },
    .{ .glyph = "🙋‍♂", .name = "man raising hand" },
    .{ .glyph = "🙋‍♀", .name = "woman raising hand" },
    .{ .glyph = "🧏", .name = "deaf person" },
    .{ .glyph = "🧏‍♂", .name = "deaf man" },
    .{ .glyph = "🧏‍♀", .name = "deaf woman" },
    .{ .glyph = "🙇", .name = "person bowing" },
    .{ .glyph = "🙇‍♂", .name = "man bowing" },
    .{ .glyph = "🙇‍♀", .name = "woman bowing" },
    .{ .glyph = "🤦", .name = "person facepalming" },
    .{ .glyph = "🤦‍♂", .name = "man facepalming" },
    .{ .glyph = "🤦‍♀", .name = "woman facepalming" },
    .{ .glyph = "🤷", .name = "person shrugging" },
    .{ .glyph = "🤷‍♂", .name = "man shrugging" },
    .{ .glyph = "🤷‍♀", .name = "woman shrugging" },
    .{ .glyph = "🧑‍⚕", .name = "health worker" },
    .{ .glyph = "👨‍⚕", .name = "man health worker" },
    .{ .glyph = "👩‍⚕", .name = "woman health worker" },
    .{ .glyph = "🧑‍🎓", .name = "student" },
    .{ .glyph = "👨‍🎓", .name = "man student" },
    .{ .glyph = "👩‍🎓", .name = "woman student" },
    .{ .glyph = "🧑‍🏫", .name = "teacher" },
    .{ .glyph = "👨‍🏫", .name = "man teacher" },
    .{ .glyph = "👩‍🏫", .name = "woman teacher" },
    .{ .glyph = "🧑‍⚖", .name = "judge" },
    .{ .glyph = "👨‍⚖", .name = "man judge" },
    .{ .glyph = "👩‍⚖", .name = "woman judge" },
    .{ .glyph = "🧑‍🌾", .name = "farmer" },
    .{ .glyph = "👨‍🌾", .name = "man farmer" },
    .{ .glyph = "👩‍🌾", .name = "woman farmer" },
    .{ .glyph = "🧑‍🍳", .name = "cook" },
    .{ .glyph = "👨‍🍳", .name = "man cook" },
    .{ .glyph = "👩‍🍳", .name = "woman cook" },
    .{ .glyph = "🧑‍🔧", .name = "mechanic" },
    .{ .glyph = "👨‍🔧", .name = "man mechanic" },
    .{ .glyph = "👩‍🔧", .name = "woman mechanic" },
    .{ .glyph = "🧑‍🏭", .name = "factory worker" },
    .{ .glyph = "👨‍🏭", .name = "man factory worker" },
    .{ .glyph = "👩‍🏭", .name = "woman factory worker" },
    .{ .glyph = "🧑‍💼", .name = "office worker" },
    .{ .glyph = "👨‍💼", .name = "man office worker" },
    .{ .glyph = "👩‍💼", .name = "woman office worker" },
    .{ .glyph = "🧑‍🔬", .name = "scientist" },
    .{ .glyph = "👨‍🔬", .name = "man scientist" },
    .{ .glyph = "👩‍🔬", .name = "woman scientist" },
    .{ .glyph = "🧑‍💻", .name = "technologist" },
    .{ .glyph = "👨‍💻", .name = "man technologist" },
    .{ .glyph = "👩‍💻", .name = "woman technologist" },
    .{ .glyph = "🧑‍🎤", .name = "singer" },
    .{ .glyph = "👨‍🎤", .name = "man singer" },
    .{ .glyph = "👩‍🎤", .name = "woman singer" },
    .{ .glyph = "🧑‍🎨", .name = "artist" },
    .{ .glyph = "👨‍🎨", .name = "man artist" },
    .{ .glyph = "👩‍🎨", .name = "woman artist" },
    .{ .glyph = "🧑‍✈", .name = "pilot" },
    .{ .glyph = "👨‍✈", .name = "man pilot" },
    .{ .glyph = "👩‍✈", .name = "woman pilot" },
    .{ .glyph = "🧑‍🚀", .name = "astronaut" },
    .{ .glyph = "👨‍🚀", .name = "man astronaut" },
    .{ .glyph = "👩‍🚀", .name = "woman astronaut" },
    .{ .glyph = "🧑‍🚒", .name = "firefighter" },
    .{ .glyph = "👨‍🚒", .name = "man firefighter" },
    .{ .glyph = "👩‍🚒", .name = "woman firefighter" },
    .{ .glyph = "👮", .name = "police officer" },
    .{ .glyph = "👮‍♂", .name = "man police officer" },
    .{ .glyph = "👮‍♀", .name = "woman police officer" },
    .{ .glyph = "🕵", .name = "detective" },
    .{ .glyph = "🕵‍♂", .name = "man detective" },
    .{ .glyph = "🕵‍♀", .name = "woman detective" },
    .{ .glyph = "💂", .name = "guard" },
    .{ .glyph = "💂‍♂", .name = "man guard" },
    .{ .glyph = "💂‍♀", .name = "woman guard" },
    .{ .glyph = "🥷", .name = "ninja" },
    .{ .glyph = "👷", .name = "construction worker" },
    .{ .glyph = "👷‍♂", .name = "man construction worker" },
    .{ .glyph = "👷‍♀", .name = "woman construction worker" },
    .{ .glyph = "🫅", .name = "person with crown" },
    .{ .glyph = "🤴", .name = "prince" },
    .{ .glyph = "👸", .name = "princess" },
    .{ .glyph = "👳", .name = "person wearing turban" },
    .{ .glyph = "👳‍♂", .name = "man wearing turban" },
    .{ .glyph = "👳‍♀", .name = "woman wearing turban" },
    .{ .glyph = "👲", .name = "person with skullcap" },
    .{ .glyph = "🧕", .name = "woman with headscarf" },
    .{ .glyph = "🤵", .name = "person in tuxedo" },
    .{ .glyph = "🤵‍♂", .name = "man in tuxedo" },
    .{ .glyph = "🤵‍♀", .name = "woman in tuxedo" },
    .{ .glyph = "👰", .name = "person with veil" },
    .{ .glyph = "👰‍♂", .name = "man with veil" },
    .{ .glyph = "👰‍♀", .name = "woman with veil" },
    .{ .glyph = "🤰", .name = "pregnant woman" },
    .{ .glyph = "🫃", .name = "pregnant man" },
    .{ .glyph = "🫄", .name = "pregnant person" },
    .{ .glyph = "🤱", .name = "breast-feeding" },
    .{ .glyph = "👩‍🍼", .name = "woman feeding baby" },
    .{ .glyph = "👨‍🍼", .name = "man feeding baby" },
    .{ .glyph = "🧑‍🍼", .name = "person feeding baby" },
    .{ .glyph = "👼", .name = "baby angel" },
    .{ .glyph = "🎅", .name = "Santa Claus" },
    .{ .glyph = "🤶", .name = "Mrs. Claus" },
    .{ .glyph = "🧑‍🎄", .name = "mx claus" },
    .{ .glyph = "🦸", .name = "superhero" },
    .{ .glyph = "🦸‍♂", .name = "man superhero" },
    .{ .glyph = "🦸‍♀", .name = "woman superhero" },
    .{ .glyph = "🦹", .name = "supervillain" },
    .{ .glyph = "🦹‍♂", .name = "man supervillain" },
    .{ .glyph = "🦹‍♀", .name = "woman supervillain" },
    .{ .glyph = "🧙", .name = "mage" },
    .{ .glyph = "🧙‍♂", .name = "man mage" },
    .{ .glyph = "🧙‍♀", .name = "woman mage" },
    .{ .glyph = "🧚", .name = "fairy" },
    .{ .glyph = "🧚‍♂", .name = "man fairy" },
    .{ .glyph = "🧚‍♀", .name = "woman fairy" },
    .{ .glyph = "🧛", .name = "vampire" },
    .{ .glyph = "🧛‍♂", .name = "man vampire" },
    .{ .glyph = "🧛‍♀", .name = "woman vampire" },
    .{ .glyph = "🧜", .name = "merperson" },
    .{ .glyph = "🧜‍♂", .name = "merman" },
    .{ .glyph = "🧜‍♀", .name = "mermaid" },
    .{ .glyph = "🧝", .name = "elf" },
    .{ .glyph = "🧝‍♂", .name = "man elf" },
    .{ .glyph = "🧝‍♀", .name = "woman elf" },
    .{ .glyph = "🧞", .name = "genie" },
    .{ .glyph = "🧞‍♂", .name = "man genie" },
    .{ .glyph = "🧞‍♀", .name = "woman genie" },
    .{ .glyph = "🧟", .name = "zombie" },
    .{ .glyph = "🧟‍♂", .name = "man zombie" },
    .{ .glyph = "🧟‍♀", .name = "woman zombie" },
    .{ .glyph = "🧌", .name = "troll" },
    .{ .glyph = "💆", .name = "person getting massage" },
    .{ .glyph = "💆‍♂", .name = "man getting massage" },
    .{ .glyph = "💆‍♀", .name = "woman getting massage" },
    .{ .glyph = "💇", .name = "person getting haircut" },
    .{ .glyph = "💇‍♂", .name = "man getting haircut" },
    .{ .glyph = "💇‍♀", .name = "woman getting haircut" },
    .{ .glyph = "🚶", .name = "person walking" },
    .{ .glyph = "🚶‍♂", .name = "man walking" },
    .{ .glyph = "🚶‍♀", .name = "woman walking" },
    .{ .glyph = "🧍", .name = "person standing" },
    .{ .glyph = "🧍‍♂", .name = "man standing" },
    .{ .glyph = "🧍‍♀", .name = "woman standing" },
    .{ .glyph = "🧎", .name = "person kneeling" },
    .{ .glyph = "🧎‍♂", .name = "man kneeling" },
    .{ .glyph = "🧎‍♀", .name = "woman kneeling" },
    .{ .glyph = "🧑‍🦯", .name = "person with white cane" },
    .{ .glyph = "👨‍🦯", .name = "man with white cane" },
    .{ .glyph = "👩‍🦯", .name = "woman with white cane" },
    .{ .glyph = "🧑‍🦼", .name = "person in motorized wheelchair" },
    .{ .glyph = "👨‍🦼", .name = "man in motorized wheelchair" },
    .{ .glyph = "👩‍🦼", .name = "woman in motorized wheelchair" },
    .{ .glyph = "🧑‍🦽", .name = "person in manual wheelchair" },
    .{ .glyph = "👨‍🦽", .name = "man in manual wheelchair" },
    .{ .glyph = "👩‍🦽", .name = "woman in manual wheelchair" },
    .{ .glyph = "🏃", .name = "person running" },
    .{ .glyph = "🏃‍♂", .name = "man running" },
    .{ .glyph = "🏃‍♀", .name = "woman running" },
    .{ .glyph = "💃", .name = "woman dancing" },
    .{ .glyph = "🕺", .name = "man dancing" },
    .{ .glyph = "🕴", .name = "person in suit levitating" },
    .{ .glyph = "👯", .name = "people with bunny ears" },
    .{ .glyph = "👯‍♂", .name = "men with bunny ears" },
    .{ .glyph = "👯‍♀", .name = "women with bunny ears" },
    .{ .glyph = "🧖", .name = "person in steamy room" },
    .{ .glyph = "🧖‍♂", .name = "man in steamy room" },
    .{ .glyph = "🧖‍♀", .name = "woman in steamy room" },
    .{ .glyph = "🧗", .name = "person climbing" },
    .{ .glyph = "🧗‍♂", .name = "man climbing" },
    .{ .glyph = "🧗‍♀", .name = "woman climbing" },
    .{ .glyph = "🤺", .name = "person fencing" },
    .{ .glyph = "🏇", .name = "horse racing" },
    .{ .glyph = "🏂", .name = "snowboarder" },
    .{ .glyph = "🏌", .name = "person golfing" },
    .{ .glyph = "🏌‍♂", .name = "man golfing" },
    .{ .glyph = "🏌‍♀", .name = "woman golfing" },
    .{ .glyph = "🏄", .name = "person surfing" },
    .{ .glyph = "🏄‍♂", .name = "man surfing" },
    .{ .glyph = "🏄‍♀", .name = "woman surfing" },
    .{ .glyph = "🚣", .name = "person rowing boat" },
    .{ .glyph = "🚣‍♂", .name = "man rowing boat" },
    .{ .glyph = "🚣‍♀", .name = "woman rowing boat" },
    .{ .glyph = "🏊", .name = "person swimming" },
    .{ .glyph = "🏊‍♂", .name = "man swimming" },
    .{ .glyph = "🏊‍♀", .name = "woman swimming" },
    .{ .glyph = "🏋", .name = "person lifting weights" },
    .{ .glyph = "🏋‍♂", .name = "man lifting weights" },
    .{ .glyph = "🏋‍♀", .name = "woman lifting weights" },
    .{ .glyph = "🚴", .name = "person biking" },
    .{ .glyph = "🚴‍♂", .name = "man biking" },
    .{ .glyph = "🚴‍♀", .name = "woman biking" },
    .{ .glyph = "🚵", .name = "person mountain biking" },
    .{ .glyph = "🚵‍♂", .name = "man mountain biking" },
    .{ .glyph = "🚵‍♀", .name = "woman mountain biking" },
    .{ .glyph = "🤸", .name = "person cartwheeling" },
    .{ .glyph = "🤸‍♂", .name = "man cartwheeling" },
    .{ .glyph = "🤸‍♀", .name = "woman cartwheeling" },
    .{ .glyph = "🤼", .name = "people wrestling" },
    .{ .glyph = "🤼‍♂", .name = "men wrestling" },
    .{ .glyph = "🤼‍♀", .name = "women wrestling" },
    .{ .glyph = "🤽", .name = "person playing water polo" },
    .{ .glyph = "🤽‍♂", .name = "man playing water polo" },
    .{ .glyph = "🤽‍♀", .name = "woman playing water polo" },
    .{ .glyph = "🤾", .name = "person playing handball" },
    .{ .glyph = "🤾‍♂", .name = "man playing handball" },
    .{ .glyph = "🤾‍♀", .name = "woman playing handball" },
    .{ .glyph = "🤹", .name = "person juggling" },
    .{ .glyph = "🤹‍♂", .name = "man juggling" },
    .{ .glyph = "🤹‍♀", .name = "woman juggling" },
    .{ .glyph = "🧘", .name = "person in lotus position" },
    .{ .glyph = "🧘‍♂", .name = "man in lotus position" },
    .{ .glyph = "🧘‍♀", .name = "woman in lotus position" },
    .{ .glyph = "🛀", .name = "person taking bath" },
    .{ .glyph = "🛌", .name = "person in bed" },
    .{ .glyph = "🧑‍🤝‍🧑", .name = "people holding hands" },
    .{ .glyph = "👭", .name = "women holding hands" },
    .{ .glyph = "👫", .name = "woman and man holding hands" },
    .{ .glyph = "👬", .name = "men holding hands" },
    .{ .glyph = "💏", .name = "kiss" },
    .{ .glyph = "💑", .name = "couple with heart" },
    .{ .glyph = "🗣", .name = "speaking head" },
    .{ .glyph = "👤", .name = "bust in silhouette" },
    .{ .glyph = "👥", .name = "busts in silhouette" },
    .{ .glyph = "🫂", .name = "people hugging" },
    .{ .glyph = "👪", .name = "family" },
    .{ .glyph = "🧑‍🧑‍🧒", .name = "family adult, adult, child" },
    .{ .glyph = "🧑‍🧑‍🧒‍🧒", .name = "family adult, adult, child, child" },
    .{ .glyph = "🧑‍🧒", .name = "family adult, child" },
    .{ .glyph = "🧑‍🧒‍🧒", .name = "family adult, child, child" },
    .{ .glyph = "👣", .name = "footprints" },
    .{ .glyph = "🦰", .name = "red hair" },
    .{ .glyph = "🦱", .name = "curly hair" },
    .{ .glyph = "🦳", .name = "white hair" },
    .{ .glyph = "🦲", .name = "bald" },
    .{ .glyph = "🐵", .name = "monkey face" },
    .{ .glyph = "🐒", .name = "monkey" },
    .{ .glyph = "🦍", .name = "gorilla" },
    .{ .glyph = "🦧", .name = "orangutan" },
    .{ .glyph = "🐶", .name = "dog face" },
    .{ .glyph = "🐕", .name = "dog" },
    .{ .glyph = "🦮", .name = "guide dog" },
    .{ .glyph = "🐕‍🦺", .name = "service dog" },
    .{ .glyph = "🐩", .name = "poodle" },
    .{ .glyph = "🐺", .name = "wolf" },
    .{ .glyph = "🦊", .name = "fox" },
    .{ .glyph = "🦝", .name = "raccoon" },
    .{ .glyph = "🐱", .name = "cat face" },
    .{ .glyph = "🐈", .name = "cat" },
    .{ .glyph = "🐈‍⬛", .name = "black cat" },
    .{ .glyph = "🦁", .name = "lion" },
    .{ .glyph = "🐯", .name = "tiger face" },
    .{ .glyph = "🐅", .name = "tiger" },
    .{ .glyph = "🐆", .name = "leopard" },
    .{ .glyph = "🐴", .name = "horse face" },
    .{ .glyph = "🫎", .name = "moose" },
    .{ .glyph = "🫏", .name = "donkey" },
    .{ .glyph = "🐎", .name = "horse" },
    .{ .glyph = "🦄", .name = "unicorn" },
    .{ .glyph = "🦓", .name = "zebra" },
    .{ .glyph = "🦌", .name = "deer" },
    .{ .glyph = "🦬", .name = "bison" },
    .{ .glyph = "🐮", .name = "cow face" },
    .{ .glyph = "🐂", .name = "ox" },
    .{ .glyph = "🐃", .name = "water buffalo" },
    .{ .glyph = "🐄", .name = "cow" },
    .{ .glyph = "🐷", .name = "pig face" },
    .{ .glyph = "🐖", .name = "pig" },
    .{ .glyph = "🐗", .name = "boar" },
    .{ .glyph = "🐽", .name = "pig nose" },
    .{ .glyph = "🐏", .name = "ram" },
    .{ .glyph = "🐑", .name = "ewe" },
    .{ .glyph = "🐐", .name = "goat" },
    .{ .glyph = "🐪", .name = "camel" },
    .{ .glyph = "🐫", .name = "two-hump camel" },
    .{ .glyph = "🦙", .name = "llama" },
    .{ .glyph = "🦒", .name = "giraffe" },
    .{ .glyph = "🐘", .name = "elephant" },
    .{ .glyph = "🦣", .name = "mammoth" },
    .{ .glyph = "🦏", .name = "rhinoceros" },
    .{ .glyph = "🦛", .name = "hippopotamus" },
    .{ .glyph = "🐭", .name = "mouse face" },
    .{ .glyph = "🐁", .name = "mouse" },
    .{ .glyph = "🐀", .name = "rat" },
    .{ .glyph = "🐹", .name = "hamster" },
    .{ .glyph = "🐰", .name = "rabbit face" },
    .{ .glyph = "🐇", .name = "rabbit" },
    .{ .glyph = "🐿", .name = "chipmunk" },
    .{ .glyph = "🦫", .name = "beaver" },
    .{ .glyph = "🦔", .name = "hedgehog" },
    .{ .glyph = "🦇", .name = "bat" },
    .{ .glyph = "🐻", .name = "bear" },
    .{ .glyph = "🐻‍❄", .name = "polar bear" },
    .{ .glyph = "🐨", .name = "koala" },
    .{ .glyph = "🐼", .name = "panda" },
    .{ .glyph = "🦥", .name = "sloth" },
    .{ .glyph = "🦦", .name = "otter" },
    .{ .glyph = "🦨", .name = "skunk" },
    .{ .glyph = "🦘", .name = "kangaroo" },
    .{ .glyph = "🦡", .name = "badger" },
    .{ .glyph = "🐾", .name = "paw prints" },
    .{ .glyph = "🦃", .name = "turkey" },
    .{ .glyph = "🐔", .name = "chicken" },
    .{ .glyph = "🐓", .name = "rooster" },
    .{ .glyph = "🐣", .name = "hatching chick" },
    .{ .glyph = "🐤", .name = "baby chick" },
    .{ .glyph = "🐥", .name = "front-facing baby chick" },
    .{ .glyph = "🐦", .name = "bird" },
    .{ .glyph = "🐧", .name = "penguin" },
    .{ .glyph = "🕊", .name = "dove" },
    .{ .glyph = "🦅", .name = "eagle" },
    .{ .glyph = "🦆", .name = "duck" },
    .{ .glyph = "🦢", .name = "swan" },
    .{ .glyph = "🦉", .name = "owl" },
    .{ .glyph = "🦤", .name = "dodo" },
    .{ .glyph = "🪶", .name = "feather" },
    .{ .glyph = "🦩", .name = "flamingo" },
    .{ .glyph = "🦚", .name = "peacock" },
    .{ .glyph = "🦜", .name = "parrot" },
    .{ .glyph = "🪽", .name = "wing" },
    .{ .glyph = "🐦‍⬛", .name = "black bird" },
    .{ .glyph = "🪿", .name = "goose" },
    .{ .glyph = "🐦‍🔥", .name = "phoenix" },
    .{ .glyph = "🐸", .name = "frog" },
    .{ .glyph = "🐊", .name = "crocodile" },
    .{ .glyph = "🐢", .name = "turtle" },
    .{ .glyph = "🦎", .name = "lizard" },
    .{ .glyph = "🐍", .name = "snake" },
    .{ .glyph = "🐲", .name = "dragon face" },
    .{ .glyph = "🐉", .name = "dragon" },
    .{ .glyph = "🦕", .name = "sauropod" },
    .{ .glyph = "🦖", .name = "T-Rex" },
    .{ .glyph = "🐳", .name = "spouting whale" },
    .{ .glyph = "🐋", .name = "whale" },
    .{ .glyph = "🐬", .name = "dolphin" },
    .{ .glyph = "🦭", .name = "seal" },
    .{ .glyph = "🐟", .name = "fish" },
    .{ .glyph = "🐠", .name = "tropical fish" },
    .{ .glyph = "🐡", .name = "blowfish" },
    .{ .glyph = "🦈", .name = "shark" },
    .{ .glyph = "🐙", .name = "octopus" },
    .{ .glyph = "🐚", .name = "spiral shell" },
    .{ .glyph = "🪸", .name = "coral" },
    .{ .glyph = "🪼", .name = "jellyfish" },
    .{ .glyph = "🐌", .name = "snail" },
    .{ .glyph = "🦋", .name = "butterfly" },
    .{ .glyph = "🐛", .name = "bug" },
    .{ .glyph = "🐜", .name = "ant" },
    .{ .glyph = "🐝", .name = "honeybee" },
    .{ .glyph = "🪲", .name = "beetle" },
    .{ .glyph = "🐞", .name = "lady beetle" },
    .{ .glyph = "🦗", .name = "cricket" },
    .{ .glyph = "🪳", .name = "cockroach" },
    .{ .glyph = "🕷", .name = "spider" },
    .{ .glyph = "🕸", .name = "spider web" },
    .{ .glyph = "🦂", .name = "scorpion" },
    .{ .glyph = "🦟", .name = "mosquito" },
    .{ .glyph = "🪰", .name = "fly" },
    .{ .glyph = "🪱", .name = "worm" },
    .{ .glyph = "🦠", .name = "microbe" },
    .{ .glyph = "💐", .name = "bouquet" },
    .{ .glyph = "🌸", .name = "cherry blossom" },
    .{ .glyph = "💮", .name = "white flower" },
    .{ .glyph = "🪷", .name = "lotus" },
    .{ .glyph = "🏵", .name = "rosette" },
    .{ .glyph = "🌹", .name = "rose" },
    .{ .glyph = "🥀", .name = "wilted flower" },
    .{ .glyph = "🌺", .name = "hibiscus" },
    .{ .glyph = "🌻", .name = "sunflower" },
    .{ .glyph = "🌼", .name = "blossom" },
    .{ .glyph = "🌷", .name = "tulip" },
    .{ .glyph = "🪻", .name = "hyacinth" },
    .{ .glyph = "🌱", .name = "seedling" },
    .{ .glyph = "🪴", .name = "potted plant" },
    .{ .glyph = "🌲", .name = "evergreen tree" },
    .{ .glyph = "🌳", .name = "deciduous tree" },
    .{ .glyph = "🌴", .name = "palm tree" },
    .{ .glyph = "🌵", .name = "cactus" },
    .{ .glyph = "🌾", .name = "sheaf of rice" },
    .{ .glyph = "🌿", .name = "herb" },
    .{ .glyph = "🍀", .name = "four leaf clover" },
    .{ .glyph = "🍁", .name = "maple leaf" },
    .{ .glyph = "🍂", .name = "fallen leaf" },
    .{ .glyph = "🍃", .name = "leaf fluttering in wind" },
    .{ .glyph = "🪹", .name = "empty nest" },
    .{ .glyph = "🪺", .name = "nest with eggs" },
    .{ .glyph = "🍄", .name = "mushroom" },
    .{ .glyph = "🍇", .name = "grapes" },
    .{ .glyph = "🍈", .name = "melon" },
    .{ .glyph = "🍉", .name = "watermelon" },
    .{ .glyph = "🍊", .name = "tangerine" },
    .{ .glyph = "🍋", .name = "lemon" },
    .{ .glyph = "🍋‍🟩", .name = "lime" },
    .{ .glyph = "🍌", .name = "banana" },
    .{ .glyph = "🍍", .name = "pineapple" },
    .{ .glyph = "🥭", .name = "mango" },
    .{ .glyph = "🍎", .name = "red apple" },
    .{ .glyph = "🍏", .name = "green apple" },
    .{ .glyph = "🍐", .name = "pear" },
    .{ .glyph = "🍑", .name = "peach" },
    .{ .glyph = "🍒", .name = "cherries" },
    .{ .glyph = "🍓", .name = "strawberry" },
    .{ .glyph = "🫐", .name = "blueberries" },
    .{ .glyph = "🥝", .name = "kiwi fruit" },
    .{ .glyph = "🍅", .name = "tomato" },
    .{ .glyph = "🫒", .name = "olive" },
    .{ .glyph = "🥥", .name = "coconut" },
    .{ .glyph = "🥑", .name = "avocado" },
    .{ .glyph = "🍆", .name = "eggplant" },
    .{ .glyph = "🥔", .name = "potato" },
    .{ .glyph = "🥕", .name = "carrot" },
    .{ .glyph = "🌽", .name = "ear of corn" },
    .{ .glyph = "🌶", .name = "hot pepper" },
    .{ .glyph = "🫑", .name = "bell pepper" },
    .{ .glyph = "🥒", .name = "cucumber" },
    .{ .glyph = "🥬", .name = "leafy green" },
    .{ .glyph = "🥦", .name = "broccoli" },
    .{ .glyph = "🧄", .name = "garlic" },
    .{ .glyph = "🧅", .name = "onion" },
    .{ .glyph = "🥜", .name = "peanuts" },
    .{ .glyph = "🫘", .name = "beans" },
    .{ .glyph = "🌰", .name = "chestnut" },
    .{ .glyph = "🫚", .name = "ginger root" },
    .{ .glyph = "🫛", .name = "pea pod" },
    .{ .glyph = "🍄‍🟫", .name = "brown mushroom" },
    .{ .glyph = "🍞", .name = "bread" },
    .{ .glyph = "🥐", .name = "croissant" },
    .{ .glyph = "🥖", .name = "baguette bread" },
    .{ .glyph = "🫓", .name = "flatbread" },
    .{ .glyph = "🥨", .name = "pretzel" },
    .{ .glyph = "🥯", .name = "bagel" },
    .{ .glyph = "🥞", .name = "pancakes" },
    .{ .glyph = "🧇", .name = "waffle" },
    .{ .glyph = "🧀", .name = "cheese wedge" },
    .{ .glyph = "🍖", .name = "meat on bone" },
    .{ .glyph = "🍗", .name = "poultry leg" },
    .{ .glyph = "🥩", .name = "cut of meat" },
    .{ .glyph = "🥓", .name = "bacon" },
    .{ .glyph = "🍔", .name = "hamburger" },
    .{ .glyph = "🍟", .name = "french fries" },
    .{ .glyph = "🍕", .name = "pizza" },
    .{ .glyph = "🌭", .name = "hot dog" },
    .{ .glyph = "🥪", .name = "sandwich" },
    .{ .glyph = "🌮", .name = "taco" },
    .{ .glyph = "🌯", .name = "burrito" },
    .{ .glyph = "🫔", .name = "tamale" },
    .{ .glyph = "🥙", .name = "stuffed flatbread" },
    .{ .glyph = "🧆", .name = "falafel" },
    .{ .glyph = "🥚", .name = "egg" },
    .{ .glyph = "🍳", .name = "cooking" },
    .{ .glyph = "🥘", .name = "shallow pan of food" },
    .{ .glyph = "🍲", .name = "pot of food" },
    .{ .glyph = "🫕", .name = "fondue" },
    .{ .glyph = "🥣", .name = "bowl with spoon" },
    .{ .glyph = "🥗", .name = "green salad" },
    .{ .glyph = "🍿", .name = "popcorn" },
    .{ .glyph = "🧈", .name = "butter" },
    .{ .glyph = "🧂", .name = "salt" },
    .{ .glyph = "🥫", .name = "canned food" },
    .{ .glyph = "🍱", .name = "bento box" },
    .{ .glyph = "🍘", .name = "rice cracker" },
    .{ .glyph = "🍙", .name = "rice ball" },
    .{ .glyph = "🍚", .name = "cooked rice" },
    .{ .glyph = "🍛", .name = "curry rice" },
    .{ .glyph = "🍜", .name = "steaming bowl" },
    .{ .glyph = "🍝", .name = "spaghetti" },
    .{ .glyph = "🍠", .name = "roasted sweet potato" },
    .{ .glyph = "🍢", .name = "oden" },
    .{ .glyph = "🍣", .name = "sushi" },
    .{ .glyph = "🍤", .name = "fried shrimp" },
    .{ .glyph = "🍥", .name = "fish cake with swirl" },
    .{ .glyph = "🥮", .name = "moon cake" },
    .{ .glyph = "🍡", .name = "dango" },
    .{ .glyph = "🥟", .name = "dumpling" },
    .{ .glyph = "🥠", .name = "fortune cookie" },
    .{ .glyph = "🥡", .name = "takeout box" },
    .{ .glyph = "🦀", .name = "crab" },
    .{ .glyph = "🦞", .name = "lobster" },
    .{ .glyph = "🦐", .name = "shrimp" },
    .{ .glyph = "🦑", .name = "squid" },
    .{ .glyph = "🦪", .name = "oyster" },
    .{ .glyph = "🍦", .name = "soft ice cream" },
    .{ .glyph = "🍧", .name = "shaved ice" },
    .{ .glyph = "🍨", .name = "ice cream" },
    .{ .glyph = "🍩", .name = "doughnut" },
    .{ .glyph = "🍪", .name = "cookie" },
    .{ .glyph = "🎂", .name = "birthday cake" },
    .{ .glyph = "🍰", .name = "shortcake" },
    .{ .glyph = "🧁", .name = "cupcake" },
    .{ .glyph = "🥧", .name = "pie" },
    .{ .glyph = "🍫", .name = "chocolate bar" },
    .{ .glyph = "🍬", .name = "candy" },
    .{ .glyph = "🍭", .name = "lollipop" },
    .{ .glyph = "🍮", .name = "custard" },
    .{ .glyph = "🍯", .name = "honey pot" },
    .{ .glyph = "🍼", .name = "baby bottle" },
    .{ .glyph = "🥛", .name = "glass of milk" },
    .{ .glyph = "🫖", .name = "teapot" },
    .{ .glyph = "🍵", .name = "teacup without handle" },
    .{ .glyph = "🍶", .name = "sake" },
    .{ .glyph = "🍾", .name = "bottle with popping cork" },
    .{ .glyph = "🍷", .name = "wine glass" },
    .{ .glyph = "🍸", .name = "cocktail glass" },
    .{ .glyph = "🍹", .name = "tropical drink" },
    .{ .glyph = "🍺", .name = "beer mug" },
    .{ .glyph = "🍻", .name = "clinking beer mugs" },
    .{ .glyph = "🥂", .name = "clinking glasses" },
    .{ .glyph = "🥃", .name = "tumbler glass" },
    .{ .glyph = "🫗", .name = "pouring liquid" },
    .{ .glyph = "🥤", .name = "cup with straw" },
    .{ .glyph = "🧋", .name = "bubble tea" },
    .{ .glyph = "🧃", .name = "beverage box" },
    .{ .glyph = "🧉", .name = "mate" },
    .{ .glyph = "🧊", .name = "ice" },
    .{ .glyph = "🥢", .name = "chopsticks" },
    .{ .glyph = "🍽", .name = "fork and knife with plate" },
    .{ .glyph = "🍴", .name = "fork and knife" },
    .{ .glyph = "🥄", .name = "spoon" },
    .{ .glyph = "🔪", .name = "kitchen knife" },
    .{ .glyph = "🫙", .name = "jar" },
    .{ .glyph = "🏺", .name = "amphora" },
    .{ .glyph = "🌍", .name = "globe showing Europe-Africa" },
    .{ .glyph = "🌎", .name = "globe showing Americas" },
    .{ .glyph = "🌏", .name = "globe showing Asia-Australia" },
    .{ .glyph = "🌐", .name = "globe with meridians" },
    .{ .glyph = "🗺", .name = "world map" },
    .{ .glyph = "🗾", .name = "map of Japan" },
    .{ .glyph = "🧭", .name = "compass" },
    .{ .glyph = "🏔", .name = "snow-capped mountain" },
    .{ .glyph = "🌋", .name = "volcano" },
    .{ .glyph = "🗻", .name = "mount fuji" },
    .{ .glyph = "🏕", .name = "camping" },
    .{ .glyph = "🏖", .name = "beach with umbrella" },
    .{ .glyph = "🏜", .name = "desert" },
    .{ .glyph = "🏝", .name = "desert island" },
    .{ .glyph = "🏞", .name = "national park" },
    .{ .glyph = "🏟", .name = "stadium" },
    .{ .glyph = "🏛", .name = "classical building" },
    .{ .glyph = "🏗", .name = "building construction" },
    .{ .glyph = "🧱", .name = "brick" },
    .{ .glyph = "🪨", .name = "rock" },
    .{ .glyph = "🪵", .name = "wood" },
    .{ .glyph = "🛖", .name = "hut" },
    .{ .glyph = "🏘", .name = "houses" },
    .{ .glyph = "🏚", .name = "derelict house" },
    .{ .glyph = "🏠", .name = "house" },
    .{ .glyph = "🏡", .name = "house with garden" },
    .{ .glyph = "🏢", .name = "office building" },
    .{ .glyph = "🏣", .name = "Japanese post office" },
    .{ .glyph = "🏤", .name = "post office" },
    .{ .glyph = "🏥", .name = "hospital" },
    .{ .glyph = "🏦", .name = "bank" },
    .{ .glyph = "🏨", .name = "hotel" },
    .{ .glyph = "🏩", .name = "love hotel" },
    .{ .glyph = "🏪", .name = "convenience store" },
    .{ .glyph = "🏫", .name = "school" },
    .{ .glyph = "🏬", .name = "department store" },
    .{ .glyph = "🏭", .name = "factory" },
    .{ .glyph = "🏯", .name = "Japanese castle" },
    .{ .glyph = "🏰", .name = "castle" },
    .{ .glyph = "💒", .name = "wedding" },
    .{ .glyph = "🗼", .name = "Tokyo tower" },
    .{ .glyph = "🗽", .name = "Statue of Liberty" },
    .{ .glyph = "🕌", .name = "mosque" },
    .{ .glyph = "🛕", .name = "hindu temple" },
    .{ .glyph = "🕍", .name = "synagogue" },
    .{ .glyph = "🕋", .name = "kaaba" },
    .{ .glyph = "🌁", .name = "foggy" },
    .{ .glyph = "🌃", .name = "night with stars" },
    .{ .glyph = "🏙", .name = "cityscape" },
    .{ .glyph = "🌄", .name = "sunrise over mountains" },
    .{ .glyph = "🌅", .name = "sunrise" },
    .{ .glyph = "🌆", .name = "cityscape at dusk" },
    .{ .glyph = "🌇", .name = "sunset" },
    .{ .glyph = "🌉", .name = "bridge at night" },
    .{ .glyph = "🎠", .name = "carousel horse" },
    .{ .glyph = "🛝", .name = "playground slide" },
    .{ .glyph = "🎡", .name = "ferris wheel" },
    .{ .glyph = "🎢", .name = "roller coaster" },
    .{ .glyph = "💈", .name = "barber pole" },
    .{ .glyph = "🎪", .name = "circus tent" },
    .{ .glyph = "🚂", .name = "locomotive" },
    .{ .glyph = "🚃", .name = "railway car" },
    .{ .glyph = "🚄", .name = "high-speed train" },
    .{ .glyph = "🚅", .name = "bullet train" },
    .{ .glyph = "🚆", .name = "train" },
    .{ .glyph = "🚇", .name = "metro" },
    .{ .glyph = "🚈", .name = "light rail" },
    .{ .glyph = "🚉", .name = "station" },
    .{ .glyph = "🚊", .name = "tram" },
    .{ .glyph = "🚝", .name = "monorail" },
    .{ .glyph = "🚞", .name = "mountain railway" },
    .{ .glyph = "🚋", .name = "tram car" },
    .{ .glyph = "🚌", .name = "bus" },
    .{ .glyph = "🚍", .name = "oncoming bus" },
    .{ .glyph = "🚎", .name = "trolleybus" },
    .{ .glyph = "🚐", .name = "minibus" },
    .{ .glyph = "🚑", .name = "ambulance" },
    .{ .glyph = "🚒", .name = "fire engine" },
    .{ .glyph = "🚓", .name = "police car" },
    .{ .glyph = "🚔", .name = "oncoming police car" },
    .{ .glyph = "🚕", .name = "taxi" },
    .{ .glyph = "🚖", .name = "oncoming taxi" },
    .{ .glyph = "🚗", .name = "automobile" },
    .{ .glyph = "🚘", .name = "oncoming automobile" },
    .{ .glyph = "🚙", .name = "sport utility vehicle" },
    .{ .glyph = "🛻", .name = "pickup truck" },
    .{ .glyph = "🚚", .name = "delivery truck" },
    .{ .glyph = "🚛", .name = "articulated lorry" },
    .{ .glyph = "🚜", .name = "tractor" },
    .{ .glyph = "🏎", .name = "racing car" },
    .{ .glyph = "🏍", .name = "motorcycle" },
    .{ .glyph = "🛵", .name = "motor scooter" },
    .{ .glyph = "🦽", .name = "manual wheelchair" },
    .{ .glyph = "🦼", .name = "motorized wheelchair" },
    .{ .glyph = "🛺", .name = "auto rickshaw" },
    .{ .glyph = "🚲", .name = "bicycle" },
    .{ .glyph = "🛴", .name = "kick scooter" },
    .{ .glyph = "🛹", .name = "skateboard" },
    .{ .glyph = "🛼", .name = "roller skate" },
    .{ .glyph = "🚏", .name = "bus stop" },
    .{ .glyph = "🛣", .name = "motorway" },
    .{ .glyph = "🛤", .name = "railway track" },
    .{ .glyph = "🛢", .name = "oil drum" },
    .{ .glyph = "🛞", .name = "wheel" },
    .{ .glyph = "🚨", .name = "police car light" },
    .{ .glyph = "🚥", .name = "horizontal traffic light" },
    .{ .glyph = "🚦", .name = "vertical traffic light" },
    .{ .glyph = "🛑", .name = "stop sign" },
    .{ .glyph = "🚧", .name = "construction" },
    .{ .glyph = "🛟", .name = "ring buoy" },
    .{ .glyph = "🛶", .name = "canoe" },
    .{ .glyph = "🚤", .name = "speedboat" },
    .{ .glyph = "🛳", .name = "passenger ship" },
    .{ .glyph = "🛥", .name = "motor boat" },
    .{ .glyph = "🚢", .name = "ship" },
    .{ .glyph = "🛩", .name = "small airplane" },
    .{ .glyph = "🛫", .name = "airplane departure" },
    .{ .glyph = "🛬", .name = "airplane arrival" },
    .{ .glyph = "🪂", .name = "parachute" },
    .{ .glyph = "💺", .name = "seat" },
    .{ .glyph = "🚁", .name = "helicopter" },
    .{ .glyph = "🚟", .name = "suspension railway" },
    .{ .glyph = "🚠", .name = "mountain cableway" },
    .{ .glyph = "🚡", .name = "aerial tramway" },
    .{ .glyph = "🛰", .name = "satellite" },
    .{ .glyph = "🚀", .name = "rocket" },
    .{ .glyph = "🛸", .name = "flying saucer" },
    .{ .glyph = "🛎", .name = "bellhop bell" },
    .{ .glyph = "🧳", .name = "luggage" },
    .{ .glyph = "🕰", .name = "mantelpiece clock" },
    .{ .glyph = "🕛", .name = "twelve o’clock" },
    .{ .glyph = "🕧", .name = "twelve-thirty" },
    .{ .glyph = "🕐", .name = "one o’clock" },
    .{ .glyph = "🕜", .name = "one-thirty" },
    .{ .glyph = "🕑", .name = "two o’clock" },
    .{ .glyph = "🕝", .name = "two-thirty" },
    .{ .glyph = "🕒", .name = "three o’clock" },
    .{ .glyph = "🕞", .name = "three-thirty" },
    .{ .glyph = "🕓", .name = "four o’clock" },
    .{ .glyph = "🕟", .name = "four-thirty" },
    .{ .glyph = "🕔", .name = "five o’clock" },
    .{ .glyph = "🕠", .name = "five-thirty" },
    .{ .glyph = "🕕", .name = "six o’clock" },
    .{ .glyph = "🕡", .name = "six-thirty" },
    .{ .glyph = "🕖", .name = "seven o’clock" },
    .{ .glyph = "🕢", .name = "seven-thirty" },
    .{ .glyph = "🕗", .name = "eight o’clock" },
    .{ .glyph = "🕣", .name = "eight-thirty" },
    .{ .glyph = "🕘", .name = "nine o’clock" },
    .{ .glyph = "🕤", .name = "nine-thirty" },
    .{ .glyph = "🕙", .name = "ten o’clock" },
    .{ .glyph = "🕥", .name = "ten-thirty" },
    .{ .glyph = "🕚", .name = "eleven o’clock" },
    .{ .glyph = "🕦", .name = "eleven-thirty" },
    .{ .glyph = "🌑", .name = "new moon" },
    .{ .glyph = "🌒", .name = "waxing crescent moon" },
    .{ .glyph = "🌓", .name = "first quarter moon" },
    .{ .glyph = "🌔", .name = "waxing gibbous moon" },
    .{ .glyph = "🌕", .name = "full moon" },
    .{ .glyph = "🌖", .name = "waning gibbous moon" },
    .{ .glyph = "🌗", .name = "last quarter moon" },
    .{ .glyph = "🌘", .name = "waning crescent moon" },
    .{ .glyph = "🌙", .name = "crescent moon" },
    .{ .glyph = "🌚", .name = "new moon face" },
    .{ .glyph = "🌛", .name = "first quarter moon face" },
    .{ .glyph = "🌜", .name = "last quarter moon face" },
    .{ .glyph = "🌡", .name = "thermometer" },
    .{ .glyph = "🌝", .name = "full moon face" },
    .{ .glyph = "🌞", .name = "sun with face" },
    .{ .glyph = "🪐", .name = "ringed planet" },
    .{ .glyph = "🌟", .name = "glowing star" },
    .{ .glyph = "🌠", .name = "shooting star" },
    .{ .glyph = "🌌", .name = "milky way" },
    .{ .glyph = "🌤", .name = "sun behind small cloud" },
    .{ .glyph = "🌥", .name = "sun behind large cloud" },
    .{ .glyph = "🌦", .name = "sun behind rain cloud" },
    .{ .glyph = "🌧", .name = "cloud with rain" },
    .{ .glyph = "🌨", .name = "cloud with snow" },
    .{ .glyph = "🌩", .name = "cloud with lightning" },
    .{ .glyph = "🌪", .name = "tornado" },
    .{ .glyph = "🌫", .name = "fog" },
    .{ .glyph = "🌬", .name = "wind face" },
    .{ .glyph = "🌀", .name = "cyclone" },
    .{ .glyph = "🌈", .name = "rainbow" },
    .{ .glyph = "🌂", .name = "closed umbrella" },
    .{ .glyph = "🔥", .name = "fire" },
    .{ .glyph = "💧", .name = "droplet" },
    .{ .glyph = "🌊", .name = "water wave" },
    .{ .glyph = "🎃", .name = "jack-o-lantern" },
    .{ .glyph = "🎄", .name = "Christmas tree" },
    .{ .glyph = "🎆", .name = "fireworks" },
    .{ .glyph = "🎇", .name = "sparkler" },
    .{ .glyph = "🧨", .name = "firecracker" },
    .{ .glyph = "🎈", .name = "balloon" },
    .{ .glyph = "🎉", .name = "party popper" },
    .{ .glyph = "🎊", .name = "confetti ball" },
    .{ .glyph = "🎋", .name = "tanabata tree" },
    .{ .glyph = "🎍", .name = "pine decoration" },
    .{ .glyph = "🎎", .name = "Japanese dolls" },
    .{ .glyph = "🎏", .name = "carp streamer" },
    .{ .glyph = "🎐", .name = "wind chime" },
    .{ .glyph = "🎑", .name = "moon viewing ceremony" },
    .{ .glyph = "🧧", .name = "red envelope" },
    .{ .glyph = "🎀", .name = "ribbon" },
    .{ .glyph = "🎁", .name = "wrapped gift" },
    .{ .glyph = "🎗", .name = "reminder ribbon" },
    .{ .glyph = "🎟", .name = "admission tickets" },
    .{ .glyph = "🎫", .name = "ticket" },
    .{ .glyph = "🎖", .name = "military medal" },
    .{ .glyph = "🏆", .name = "trophy" },
    .{ .glyph = "🏅", .name = "sports medal" },
    .{ .glyph = "🥇", .name = "1st place medal" },
    .{ .glyph = "🥈", .name = "2nd place medal" },
    .{ .glyph = "🥉", .name = "3rd place medal" },
    .{ .glyph = "🥎", .name = "softball" },
    .{ .glyph = "🏀", .name = "basketball" },
    .{ .glyph = "🏐", .name = "volleyball" },
    .{ .glyph = "🏈", .name = "american football" },
    .{ .glyph = "🏉", .name = "rugby football" },
    .{ .glyph = "🎾", .name = "tennis" },
    .{ .glyph = "🥏", .name = "flying disc" },
    .{ .glyph = "🎳", .name = "bowling" },
    .{ .glyph = "🏏", .name = "cricket game" },
    .{ .glyph = "🏑", .name = "field hockey" },
    .{ .glyph = "🏒", .name = "ice hockey" },
    .{ .glyph = "🥍", .name = "lacrosse" },
    .{ .glyph = "🏓", .name = "ping pong" },
    .{ .glyph = "🏸", .name = "badminton" },
    .{ .glyph = "🥊", .name = "boxing glove" },
    .{ .glyph = "🥋", .name = "martial arts uniform" },
    .{ .glyph = "🥅", .name = "goal net" },
    .{ .glyph = "🎣", .name = "fishing pole" },
    .{ .glyph = "🤿", .name = "diving mask" },
    .{ .glyph = "🎽", .name = "running shirt" },
    .{ .glyph = "🎿", .name = "skis" },
    .{ .glyph = "🛷", .name = "sled" },
    .{ .glyph = "🥌", .name = "curling stone" },
    .{ .glyph = "🎯", .name = "bullseye" },
    .{ .glyph = "🪀", .name = "yo-yo" },
    .{ .glyph = "🪁", .name = "kite" },
    .{ .glyph = "🔫", .name = "water pistol" },
    .{ .glyph = "🎱", .name = "pool 8 ball" },
    .{ .glyph = "🔮", .name = "crystal ball" },
    .{ .glyph = "🪄", .name = "magic wand" },
    .{ .glyph = "🎮", .name = "video game" },
    .{ .glyph = "🕹", .name = "joystick" },
    .{ .glyph = "🎰", .name = "slot machine" },
    .{ .glyph = "🎲", .name = "game die" },
    .{ .glyph = "🧩", .name = "puzzle piece" },
    .{ .glyph = "🧸", .name = "teddy bear" },
    .{ .glyph = "🪅", .name = "piñata" },
    .{ .glyph = "🪩", .name = "mirror ball" },
    .{ .glyph = "🪆", .name = "nesting dolls" },
    .{ .glyph = "🃏", .name = "joker" },
    .{ .glyph = "🀄", .name = "mahjong red dragon" },
    .{ .glyph = "🎴", .name = "flower playing cards" },
    .{ .glyph = "🎭", .name = "performing arts" },
    .{ .glyph = "🖼", .name = "framed picture" },
    .{ .glyph = "🎨", .name = "artist palette" },
    .{ .glyph = "🧵", .name = "thread" },
    .{ .glyph = "🪡", .name = "sewing needle" },
    .{ .glyph = "🧶", .name = "yarn" },
    .{ .glyph = "🪢", .name = "knot" },
    .{ .glyph = "👓", .name = "glasses" },
    .{ .glyph = "🕶", .name = "sunglasses" },
    .{ .glyph = "🥽", .name = "goggles" },
    .{ .glyph = "🥼", .name = "lab coat" },
    .{ .glyph = "🦺", .name = "safety vest" },
    .{ .glyph = "👔", .name = "necktie" },
    .{ .glyph = "👕", .name = "t-shirt" },
    .{ .glyph = "👖", .name = "jeans" },
    .{ .glyph = "🧣", .name = "scarf" },
    .{ .glyph = "🧤", .name = "gloves" },
    .{ .glyph = "🧥", .name = "coat" },
    .{ .glyph = "🧦", .name = "socks" },
    .{ .glyph = "👗", .name = "dress" },
    .{ .glyph = "👘", .name = "kimono" },
    .{ .glyph = "🥻", .name = "sari" },
    .{ .glyph = "🩱", .name = "one-piece swimsuit" },
    .{ .glyph = "🩲", .name = "briefs" },
    .{ .glyph = "🩳", .name = "shorts" },
    .{ .glyph = "👙", .name = "bikini" },
    .{ .glyph = "👚", .name = "woman’s clothes" },
    .{ .glyph = "🪭", .name = "folding hand fan" },
    .{ .glyph = "👛", .name = "purse" },
    .{ .glyph = "👜", .name = "handbag" },
    .{ .glyph = "👝", .name = "clutch bag" },
    .{ .glyph = "🛍", .name = "shopping bags" },
    .{ .glyph = "🎒", .name = "backpack" },
    .{ .glyph = "🩴", .name = "thong sandal" },
    .{ .glyph = "👞", .name = "man’s shoe" },
    .{ .glyph = "👟", .name = "running shoe" },
    .{ .glyph = "🥾", .name = "hiking boot" },
    .{ .glyph = "🥿", .name = "flat shoe" },
    .{ .glyph = "👠", .name = "high-heeled shoe" },
    .{ .glyph = "👡", .name = "woman’s sandal" },
    .{ .glyph = "🩰", .name = "ballet shoes" },
    .{ .glyph = "👢", .name = "woman’s boot" },
    .{ .glyph = "🪮", .name = "hair pick" },
    .{ .glyph = "👑", .name = "crown" },
    .{ .glyph = "👒", .name = "woman’s hat" },
    .{ .glyph = "🎩", .name = "top hat" },
    .{ .glyph = "🎓", .name = "graduation cap" },
    .{ .glyph = "🧢", .name = "billed cap" },
    .{ .glyph = "🪖", .name = "military helmet" },
    .{ .glyph = "📿", .name = "prayer beads" },
    .{ .glyph = "💄", .name = "lipstick" },
    .{ .glyph = "💍", .name = "ring" },
    .{ .glyph = "💎", .name = "gem stone" },
    .{ .glyph = "🔇", .name = "muted speaker" },
    .{ .glyph = "🔈", .name = "speaker low volume" },
    .{ .glyph = "🔉", .name = "speaker medium volume" },
    .{ .glyph = "🔊", .name = "speaker high volume" },
    .{ .glyph = "📢", .name = "loudspeaker" },
    .{ .glyph = "📣", .name = "megaphone" },
    .{ .glyph = "📯", .name = "postal horn" },
    .{ .glyph = "🔔", .name = "bell" },
    .{ .glyph = "🔕", .name = "bell with slash" },
    .{ .glyph = "🎼", .name = "musical score" },
    .{ .glyph = "🎵", .name = "musical note" },
    .{ .glyph = "🎶", .name = "musical notes" },
    .{ .glyph = "🎙", .name = "studio microphone" },
    .{ .glyph = "🎚", .name = "level slider" },
    .{ .glyph = "🎛", .name = "control knobs" },
    .{ .glyph = "🎤", .name = "microphone" },
    .{ .glyph = "🎧", .name = "headphone" },
    .{ .glyph = "📻", .name = "radio" },
    .{ .glyph = "🎷", .name = "saxophone" },
    .{ .glyph = "🪗", .name = "accordion" },
    .{ .glyph = "🎸", .name = "guitar" },
    .{ .glyph = "🎹", .name = "musical keyboard" },
    .{ .glyph = "🎺", .name = "trumpet" },
    .{ .glyph = "🎻", .name = "violin" },
    .{ .glyph = "🪕", .name = "banjo" },
    .{ .glyph = "🥁", .name = "drum" },
    .{ .glyph = "🪘", .name = "long drum" },
    .{ .glyph = "🪇", .name = "maracas" },
    .{ .glyph = "🪈", .name = "flute" },
    .{ .glyph = "📱", .name = "mobile phone" },
    .{ .glyph = "📲", .name = "mobile phone with arrow" },
    .{ .glyph = "📞", .name = "telephone receiver" },
    .{ .glyph = "📟", .name = "pager" },
    .{ .glyph = "📠", .name = "fax machine" },
    .{ .glyph = "🔋", .name = "battery" },
    .{ .glyph = "🪫", .name = "low battery" },
    .{ .glyph = "🔌", .name = "electric plug" },
    .{ .glyph = "💻", .name = "laptop" },
    .{ .glyph = "🖥", .name = "desktop computer" },
    .{ .glyph = "🖨", .name = "printer" },
    .{ .glyph = "🖱", .name = "computer mouse" },
    .{ .glyph = "🖲", .name = "trackball" },
    .{ .glyph = "💽", .name = "computer disk" },
    .{ .glyph = "💾", .name = "floppy disk" },
    .{ .glyph = "💿", .name = "optical disk" },
    .{ .glyph = "📀", .name = "dvd" },
    .{ .glyph = "🧮", .name = "abacus" },
    .{ .glyph = "🎥", .name = "movie camera" },
    .{ .glyph = "🎞", .name = "film frames" },
    .{ .glyph = "📽", .name = "film projector" },
    .{ .glyph = "🎬", .name = "clapper board" },
    .{ .glyph = "📺", .name = "television" },
    .{ .glyph = "📷", .name = "camera" },
    .{ .glyph = "📸", .name = "camera with flash" },
    .{ .glyph = "📹", .name = "video camera" },
    .{ .glyph = "📼", .name = "videocassette" },
    .{ .glyph = "🔍", .name = "magnifying glass tilted left" },
    .{ .glyph = "🔎", .name = "magnifying glass tilted right" },
    .{ .glyph = "🕯", .name = "candle" },
    .{ .glyph = "💡", .name = "light bulb" },
    .{ .glyph = "🔦", .name = "flashlight" },
    .{ .glyph = "🏮", .name = "red paper lantern" },
    .{ .glyph = "🪔", .name = "diya lamp" },
    .{ .glyph = "📔", .name = "notebook with decorative cover" },
    .{ .glyph = "📕", .name = "closed book" },
    .{ .glyph = "📖", .name = "open book" },
    .{ .glyph = "📗", .name = "green book" },
    .{ .glyph = "📘", .name = "blue book" },
    .{ .glyph = "📙", .name = "orange book" },
    .{ .glyph = "📚", .name = "books" },
    .{ .glyph = "📓", .name = "notebook" },
    .{ .glyph = "📒", .name = "ledger" },
    .{ .glyph = "📃", .name = "page with curl" },
    .{ .glyph = "📜", .name = "scroll" },
    .{ .glyph = "📄", .name = "page facing up" },
    .{ .glyph = "📰", .name = "newspaper" },
    .{ .glyph = "🗞", .name = "rolled-up newspaper" },
    .{ .glyph = "📑", .name = "bookmark tabs" },
    .{ .glyph = "🔖", .name = "bookmark" },
    .{ .glyph = "🏷", .name = "label" },
    .{ .glyph = "💰", .name = "money bag" },
    .{ .glyph = "🪙", .name = "coin" },
    .{ .glyph = "💴", .name = "yen banknote" },
    .{ .glyph = "💵", .name = "dollar banknote" },
    .{ .glyph = "💶", .name = "euro banknote" },
    .{ .glyph = "💷", .name = "pound banknote" },
    .{ .glyph = "💸", .name = "money with wings" },
    .{ .glyph = "💳", .name = "credit card" },
    .{ .glyph = "🧾", .name = "receipt" },
    .{ .glyph = "💹", .name = "chart increasing with yen" },
    .{ .glyph = "📧", .name = "e-mail" },
    .{ .glyph = "📨", .name = "incoming envelope" },
    .{ .glyph = "📩", .name = "envelope with arrow" },
    .{ .glyph = "📤", .name = "outbox tray" },
    .{ .glyph = "📥", .name = "inbox tray" },
    .{ .glyph = "📦", .name = "package" },
    .{ .glyph = "📫", .name = "closed mailbox with raised flag" },
    .{ .glyph = "📪", .name = "closed mailbox with lowered flag" },
    .{ .glyph = "📬", .name = "open mailbox with raised flag" },
    .{ .glyph = "📭", .name = "open mailbox with lowered flag" },
    .{ .glyph = "📮", .name = "postbox" },
    .{ .glyph = "🗳", .name = "ballot box with ballot" },
    .{ .glyph = "🖋", .name = "fountain pen" },
    .{ .glyph = "🖊", .name = "pen" },
    .{ .glyph = "🖌", .name = "paintbrush" },
    .{ .glyph = "🖍", .name = "crayon" },
    .{ .glyph = "📝", .name = "memo" },
    .{ .glyph = "💼", .name = "briefcase" },
    .{ .glyph = "📁", .name = "file folder" },
    .{ .glyph = "📂", .name = "open file folder" },
    .{ .glyph = "🗂", .name = "card index dividers" },
    .{ .glyph = "📅", .name = "calendar" },
    .{ .glyph = "📆", .name = "tear-off calendar" },
    .{ .glyph = "🗒", .name = "spiral notepad" },
    .{ .glyph = "🗓", .name = "spiral calendar" },
    .{ .glyph = "📇", .name = "card index" },
    .{ .glyph = "📈", .name = "chart increasing" },
    .{ .glyph = "📉", .name = "chart decreasing" },
    .{ .glyph = "📊", .name = "bar chart" },
    .{ .glyph = "📋", .name = "clipboard" },
    .{ .glyph = "📌", .name = "pushpin" },
    .{ .glyph = "📍", .name = "round pushpin" },
    .{ .glyph = "📎", .name = "paperclip" },
    .{ .glyph = "🖇", .name = "linked paperclips" },
    .{ .glyph = "📏", .name = "straight ruler" },
    .{ .glyph = "📐", .name = "triangular ruler" },
    .{ .glyph = "🗃", .name = "card file box" },
    .{ .glyph = "🗄", .name = "file cabinet" },
    .{ .glyph = "🗑", .name = "wastebasket" },
    .{ .glyph = "🔒", .name = "locked" },
    .{ .glyph = "🔓", .name = "unlocked" },
    .{ .glyph = "🔏", .name = "locked with pen" },
    .{ .glyph = "🔐", .name = "locked with key" },
    .{ .glyph = "🔑", .name = "key" },
    .{ .glyph = "🗝", .name = "old key" },
    .{ .glyph = "🔨", .name = "hammer" },
    .{ .glyph = "🪓", .name = "axe" },
    .{ .glyph = "🛠", .name = "hammer and wrench" },
    .{ .glyph = "🗡", .name = "dagger" },
    .{ .glyph = "💣", .name = "bomb" },
    .{ .glyph = "🪃", .name = "boomerang" },
    .{ .glyph = "🏹", .name = "bow and arrow" },
    .{ .glyph = "🛡", .name = "shield" },
    .{ .glyph = "🪚", .name = "carpentry saw" },
    .{ .glyph = "🔧", .name = "wrench" },
    .{ .glyph = "🪛", .name = "screwdriver" },
    .{ .glyph = "🔩", .name = "nut and bolt" },
    .{ .glyph = "🗜", .name = "clamp" },
    .{ .glyph = "🦯", .name = "white cane" },
    .{ .glyph = "🔗", .name = "link" },
    .{ .glyph = "🪝", .name = "hook" },
    .{ .glyph = "🧰", .name = "toolbox" },
    .{ .glyph = "🧲", .name = "magnet" },
    .{ .glyph = "🪜", .name = "ladder" },
    .{ .glyph = "🧪", .name = "test tube" },
    .{ .glyph = "🧫", .name = "petri dish" },
    .{ .glyph = "🧬", .name = "dna" },
    .{ .glyph = "🔬", .name = "microscope" },
    .{ .glyph = "🔭", .name = "telescope" },
    .{ .glyph = "📡", .name = "satellite antenna" },
    .{ .glyph = "💉", .name = "syringe" },
    .{ .glyph = "🩸", .name = "drop of blood" },
    .{ .glyph = "💊", .name = "pill" },
    .{ .glyph = "🩹", .name = "adhesive bandage" },
    .{ .glyph = "🩼", .name = "crutch" },
    .{ .glyph = "🩺", .name = "stethoscope" },
    .{ .glyph = "🩻", .name = "x-ray" },
    .{ .glyph = "🚪", .name = "door" },
    .{ .glyph = "🛗", .name = "elevator" },
    .{ .glyph = "🪞", .name = "mirror" },
    .{ .glyph = "🪟", .name = "window" },
    .{ .glyph = "🛏", .name = "bed" },
    .{ .glyph = "🛋", .name = "couch and lamp" },
    .{ .glyph = "🪑", .name = "chair" },
    .{ .glyph = "🚽", .name = "toilet" },
    .{ .glyph = "🪠", .name = "plunger" },
    .{ .glyph = "🚿", .name = "shower" },
    .{ .glyph = "🛁", .name = "bathtub" },
    .{ .glyph = "🪤", .name = "mouse trap" },
    .{ .glyph = "🪒", .name = "razor" },
    .{ .glyph = "🧴", .name = "lotion bottle" },
    .{ .glyph = "🧷", .name = "safety pin" },
    .{ .glyph = "🧹", .name = "broom" },
    .{ .glyph = "🧺", .name = "basket" },
    .{ .glyph = "🧻", .name = "roll of paper" },
    .{ .glyph = "🪣", .name = "bucket" },
    .{ .glyph = "🧼", .name = "soap" },
    .{ .glyph = "🫧", .name = "bubbles" },
    .{ .glyph = "🪥", .name = "toothbrush" },
    .{ .glyph = "🧽", .name = "sponge" },
    .{ .glyph = "🧯", .name = "fire extinguisher" },
    .{ .glyph = "🛒", .name = "shopping cart" },
    .{ .glyph = "🚬", .name = "cigarette" },
    .{ .glyph = "🪦", .name = "headstone" },
    .{ .glyph = "🧿", .name = "nazar amulet" },
    .{ .glyph = "🪬", .name = "hamsa" },
    .{ .glyph = "🗿", .name = "moai" },
    .{ .glyph = "🪧", .name = "placard" },
    .{ .glyph = "🪪", .name = "identification card" },
    .{ .glyph = "🏧", .name = "ATM sign" },
    .{ .glyph = "🚮", .name = "litter in bin sign" },
    .{ .glyph = "🚰", .name = "potable water" },
    .{ .glyph = "🚹", .name = "men’s room" },
    .{ .glyph = "🚺", .name = "women’s room" },
    .{ .glyph = "🚻", .name = "restroom" },
    .{ .glyph = "🚼", .name = "baby symbol" },
    .{ .glyph = "🚾", .name = "water closet" },
    .{ .glyph = "🛂", .name = "passport control" },
    .{ .glyph = "🛃", .name = "customs" },
    .{ .glyph = "🛄", .name = "baggage claim" },
    .{ .glyph = "🛅", .name = "left luggage" },
    .{ .glyph = "🚸", .name = "children crossing" },
    .{ .glyph = "🚫", .name = "prohibited" },
    .{ .glyph = "🚳", .name = "no bicycles" },
    .{ .glyph = "🚭", .name = "no smoking" },
    .{ .glyph = "🚯", .name = "no littering" },
    .{ .glyph = "🚱", .name = "non-potable water" },
    .{ .glyph = "🚷", .name = "no pedestrians" },
    .{ .glyph = "📵", .name = "no mobile phones" },
    .{ .glyph = "🔞", .name = "no one under eighteen" },
    .{ .glyph = "🔃", .name = "clockwise vertical arrows" },
    .{ .glyph = "🔄", .name = "counterclockwise arrows button" },
    .{ .glyph = "🔙", .name = "BACK arrow" },
    .{ .glyph = "🔚", .name = "END arrow" },
    .{ .glyph = "🔛", .name = "ON! arrow" },
    .{ .glyph = "🔜", .name = "SOON arrow" },
    .{ .glyph = "🔝", .name = "TOP arrow" },
    .{ .glyph = "🛐", .name = "place of worship" },
    .{ .glyph = "🕉", .name = "om" },
    .{ .glyph = "🕎", .name = "menorah" },
    .{ .glyph = "🔯", .name = "dotted six-pointed star" },
    .{ .glyph = "🪯", .name = "khanda" },
    .{ .glyph = "🔀", .name = "shuffle tracks button" },
    .{ .glyph = "🔁", .name = "repeat button" },
    .{ .glyph = "🔂", .name = "repeat single button" },
    .{ .glyph = "🔼", .name = "upwards button" },
    .{ .glyph = "🔽", .name = "downwards button" },
    .{ .glyph = "🎦", .name = "cinema" },
    .{ .glyph = "🔅", .name = "dim button" },
    .{ .glyph = "🔆", .name = "bright button" },
    .{ .glyph = "📶", .name = "antenna bars" },
    .{ .glyph = "🛜", .name = "wireless" },
    .{ .glyph = "📳", .name = "vibration mode" },
    .{ .glyph = "📴", .name = "mobile phone off" },
    .{ .glyph = "🟰", .name = "heavy equals sign" },
    .{ .glyph = "💱", .name = "currency exchange" },
    .{ .glyph = "💲", .name = "heavy dollar sign" },
    .{ .glyph = "🔱", .name = "trident emblem" },
    .{ .glyph = "📛", .name = "name badge" },
    .{ .glyph = "🔰", .name = "Japanese symbol for beginner" },
    .{ .glyph = "🔠", .name = "input latin uppercase" },
    .{ .glyph = "🔡", .name = "input latin lowercase" },
    .{ .glyph = "🔢", .name = "input numbers" },
    .{ .glyph = "🔣", .name = "input symbols" },
    .{ .glyph = "🔤", .name = "input latin letters" },
    .{ .glyph = "🅰", .name = "A button (blood type)" },
    .{ .glyph = "🆎", .name = "AB button (blood type)" },
    .{ .glyph = "🅱", .name = "B button (blood type)" },
    .{ .glyph = "🆑", .name = "CL button" },
    .{ .glyph = "🆒", .name = "COOL button" },
    .{ .glyph = "🆓", .name = "FREE button" },
    .{ .glyph = "🆔", .name = "ID button" },
    .{ .glyph = "🆕", .name = "NEW button" },
    .{ .glyph = "🆖", .name = "NG button" },
    .{ .glyph = "🅾", .name = "O button (blood type)" },
    .{ .glyph = "🆗", .name = "OK button" },
    .{ .glyph = "🅿", .name = "P button" },
    .{ .glyph = "🆘", .name = "SOS button" },
    .{ .glyph = "🆙", .name = "UP! button" },
    .{ .glyph = "🆚", .name = "VS button" },
    .{ .glyph = "🔴", .name = "red circle" },
    .{ .glyph = "🟠", .name = "orange circle" },
    .{ .glyph = "🟡", .name = "yellow circle" },
    .{ .glyph = "🟢", .name = "green circle" },
    .{ .glyph = "🔵", .name = "blue circle" },
    .{ .glyph = "🟣", .name = "purple circle" },
    .{ .glyph = "🟤", .name = "brown circle" },
    .{ .glyph = "🟥", .name = "red square" },
    .{ .glyph = "🟧", .name = "orange square" },
    .{ .glyph = "🟨", .name = "yellow square" },
    .{ .glyph = "🟩", .name = "green square" },
    .{ .glyph = "🟦", .name = "blue square" },
    .{ .glyph = "🟪", .name = "purple square" },
    .{ .glyph = "🟫", .name = "brown square" },
    .{ .glyph = "🔶", .name = "large orange diamond" },
    .{ .glyph = "🔷", .name = "large blue diamond" },
    .{ .glyph = "🔸", .name = "small orange diamond" },
    .{ .glyph = "🔹", .name = "small blue diamond" },
    .{ .glyph = "🔺", .name = "red triangle pointed up" },
    .{ .glyph = "🔻", .name = "red triangle pointed down" },
    .{ .glyph = "💠", .name = "diamond with a dot" },
    .{ .glyph = "🔘", .name = "radio button" },
    .{ .glyph = "🔳", .name = "white square button" },
    .{ .glyph = "🔲", .name = "black square button" },
    .{ .glyph = "🏁", .name = "chequered flag" },
    .{ .glyph = "🚩", .name = "triangular flag" },
    .{ .glyph = "🎌", .name = "crossed flags" },
    .{ .glyph = "🏴", .name = "black flag" },
    .{ .glyph = "🏳", .name = "white flag" },
    .{ .glyph = "🏳‍🌈", .name = "rainbow flag" },
    .{ .glyph = "🏳‍⚧", .name = "transgender flag" },
    .{ .glyph = "🏴‍☠", .name = "pirate flag" },
    .{ .glyph = "🧑‍🦰", .name = "person red hair" },
    .{ .glyph = "🧑‍🦱", .name = "person curly hair" },
    .{ .glyph = "🧑‍🦳", .name = "person white hair" },
    .{ .glyph = "🧑‍🦲", .name = "person bald" },
    .{ .glyph = "👨‍🦰", .name = "man red hair" },
    .{ .glyph = "👨‍🦱", .name = "man curly hair" },
    .{ .glyph = "👨‍🦳", .name = "man white hair" },
    .{ .glyph = "👨‍🦲", .name = "man bald" },
    .{ .glyph = "👩‍🦰", .name = "woman red hair" },
    .{ .glyph = "👩‍🦱", .name = "woman curly hair" },
    .{ .glyph = "👩‍🦳", .name = "woman white hair" },
    .{ .glyph = "👩‍🦲", .name = "woman bald" },
    .{ .glyph = "🚶‍➡", .name = "person walking facing right" },
    .{ .glyph = "🚶🏻‍➡", .name = "person walking facing right" },
    .{ .glyph = "🚶🏼‍➡", .name = "person walking facing right" },
    .{ .glyph = "🚶🏽‍➡", .name = "person walking facing right" },
    .{ .glyph = "🚶🏾‍➡", .name = "person walking facing right" },
    .{ .glyph = "🚶🏿‍➡", .name = "person walking facing right" },
    .{ .glyph = "🚶‍♀‍➡", .name = "woman walking facing right" },
    .{ .glyph = "🚶🏻‍♀‍➡", .name = "woman walking facing right" },
    .{ .glyph = "🚶🏼‍♀‍➡", .name = "woman walking facing right" },
    .{ .glyph = "🚶🏽‍♀‍➡", .name = "woman walking facing right" },
    .{ .glyph = "🚶🏾‍♀‍➡", .name = "woman walking facing right" },
    .{ .glyph = "🚶🏿‍♀‍➡", .name = "woman walking facing right" },
    .{ .glyph = "🚶‍♂‍➡", .name = "man walking facing right" },
    .{ .glyph = "🚶🏻‍♂‍➡", .name = "man walking facing right" },
    .{ .glyph = "🚶🏼‍♂‍➡", .name = "man walking facing right" },
    .{ .glyph = "🚶🏽‍♂‍➡", .name = "man walking facing right" },
    .{ .glyph = "🚶🏾‍♂‍➡", .name = "man walking facing right" },
    .{ .glyph = "🚶🏿‍♂‍➡", .name = "man walking facing right" },
    .{ .glyph = "🧎‍➡", .name = "person kneeling facing right" },
    .{ .glyph = "🧎🏻‍➡", .name = "person kneeling facing right" },
    .{ .glyph = "🧎🏼‍➡", .name = "person kneeling facing right" },
    .{ .glyph = "🧎🏽‍➡", .name = "person kneeling facing right" },
    .{ .glyph = "🧎🏾‍➡", .name = "person kneeling facing right" },
    .{ .glyph = "🧎🏿‍➡", .name = "person kneeling facing right" },
    .{ .glyph = "🧎‍♀‍➡", .name = "woman kneeling facing right" },
    .{ .glyph = "🧎🏻‍♀‍➡", .name = "woman kneeling facing right" },
    .{ .glyph = "🧎🏼‍♀‍➡", .name = "woman kneeling facing right" },
    .{ .glyph = "🧎🏽‍♀‍➡", .name = "woman kneeling facing right" },
    .{ .glyph = "🧎🏾‍♀‍➡", .name = "woman kneeling facing right" },
    .{ .glyph = "🧎🏿‍♀‍➡", .name = "woman kneeling facing right" },
    .{ .glyph = "🧎‍♂‍➡", .name = "man kneeling facing right" },
    .{ .glyph = "🧎🏻‍♂‍➡", .name = "man kneeling facing right" },
    .{ .glyph = "🧎🏼‍♂‍➡", .name = "man kneeling facing right" },
    .{ .glyph = "🧎🏽‍♂‍➡", .name = "man kneeling facing right" },
    .{ .glyph = "🧎🏾‍♂‍➡", .name = "man kneeling facing right" },
    .{ .glyph = "🧎🏿‍♂‍➡", .name = "man kneeling facing right" },
    .{ .glyph = "🧑‍🦯‍➡", .name = "person with white cane facing right" },
    .{ .glyph = "🧑🏻‍🦯‍➡", .name = "person with white cane facing right" },
    .{ .glyph = "🧑🏼‍🦯‍➡", .name = "person with white cane facing right" },
    .{ .glyph = "🧑🏽‍🦯‍➡", .name = "person with white cane facing right" },
    .{ .glyph = "🧑🏾‍🦯‍➡", .name = "person with white cane facing right" },
    .{ .glyph = "🧑🏿‍🦯‍➡", .name = "person with white cane facing right" },
    .{ .glyph = "👨‍🦯‍➡", .name = "man with white cane facing right" },
    .{ .glyph = "👨🏻‍🦯‍➡", .name = "man with white cane facing right" },
    .{ .glyph = "👨🏼‍🦯‍➡", .name = "man with white cane facing right" },
    .{ .glyph = "👨🏽‍🦯‍➡", .name = "man with white cane facing right" },
    .{ .glyph = "👨🏾‍🦯‍➡", .name = "man with white cane facing right" },
    .{ .glyph = "👨🏿‍🦯‍➡", .name = "man with white cane facing right" },
    .{ .glyph = "👩‍🦯‍➡", .name = "woman with white cane facing right" },
    .{ .glyph = "👩🏻‍🦯‍➡", .name = "woman with white cane facing right" },
    .{ .glyph = "👩🏼‍🦯‍➡", .name = "woman with white cane facing right" },
    .{ .glyph = "👩🏽‍🦯‍➡", .name = "woman with white cane facing right" },
    .{ .glyph = "👩🏾‍🦯‍➡", .name = "woman with white cane facing right" },
    .{ .glyph = "👩🏿‍🦯‍➡", .name = "woman with white cane facing right" },
    .{ .glyph = "🧑‍🦼‍➡", .name = "person in motorized wheelchair facing right" },
    .{ .glyph = "🧑🏻‍🦼‍➡", .name = "person in motorized wheelchair facing right" },
    .{ .glyph = "🧑🏼‍🦼‍➡", .name = "person in motorized wheelchair facing right" },
    .{ .glyph = "🧑🏽‍🦼‍➡", .name = "person in motorized wheelchair facing right" },
    .{ .glyph = "🧑🏾‍🦼‍➡", .name = "person in motorized wheelchair facing right" },
    .{ .glyph = "🧑🏿‍🦼‍➡", .name = "person in motorized wheelchair facing right" },
    .{ .glyph = "👨‍🦼‍➡", .name = "man in motorized wheelchair facing right" },
    .{ .glyph = "👨🏻‍🦼‍➡", .name = "man in motorized wheelchair facing right" },
    .{ .glyph = "👨🏼‍🦼‍➡", .name = "man in motorized wheelchair facing right" },
    .{ .glyph = "👨🏽‍🦼‍➡", .name = "man in motorized wheelchair facing right" },
    .{ .glyph = "👨🏾‍🦼‍➡", .name = "man in motorized wheelchair facing right" },
    .{ .glyph = "👨🏿‍🦼‍➡", .name = "man in motorized wheelchair facing right" },
    .{ .glyph = "👩‍🦼‍➡", .name = "woman in motorized wheelchair facing right" },
    .{ .glyph = "👩🏻‍🦼‍➡", .name = "woman in motorized wheelchair facing right" },
    .{ .glyph = "👩🏼‍🦼‍➡", .name = "woman in motorized wheelchair facing right" },
    .{ .glyph = "👩🏽‍🦼‍➡", .name = "woman in motorized wheelchair facing right" },
    .{ .glyph = "👩🏾‍🦼‍➡", .name = "woman in motorized wheelchair facing right" },
    .{ .glyph = "👩🏿‍🦼‍➡", .name = "woman in motorized wheelchair facing right" },
    .{ .glyph = "🧑‍🦽‍➡", .name = "person in manual wheelchair facing right" },
    .{ .glyph = "🧑🏻‍🦽‍➡", .name = "person in manual wheelchair facing right" },
    .{ .glyph = "🧑🏼‍🦽‍➡", .name = "person in manual wheelchair facing right" },
    .{ .glyph = "🧑🏽‍🦽‍➡", .name = "person in manual wheelchair facing right" },
    .{ .glyph = "🧑🏾‍🦽‍➡", .name = "person in manual wheelchair facing right" },
    .{ .glyph = "🧑🏿‍🦽‍➡", .name = "person in manual wheelchair facing right" },
    .{ .glyph = "👨‍🦽‍➡", .name = "man in manual wheelchair facing right" },
    .{ .glyph = "👨🏻‍🦽‍➡", .name = "man in manual wheelchair facing right" },
    .{ .glyph = "👨🏼‍🦽‍➡", .name = "man in manual wheelchair facing right" },
    .{ .glyph = "👨🏽‍🦽‍➡", .name = "man in manual wheelchair facing right" },
    .{ .glyph = "👨🏾‍🦽‍➡", .name = "man in manual wheelchair facing right" },
    .{ .glyph = "👨🏿‍🦽‍➡", .name = "man in manual wheelchair facing right" },
    .{ .glyph = "👩‍🦽‍➡", .name = "woman in manual wheelchair facing right" },
    .{ .glyph = "👩🏻‍🦽‍➡", .name = "woman in manual wheelchair facing right" },
    .{ .glyph = "👩🏼‍🦽‍➡", .name = "woman in manual wheelchair facing right" },
    .{ .glyph = "👩🏽‍🦽‍➡", .name = "woman in manual wheelchair facing right" },
    .{ .glyph = "👩🏾‍🦽‍➡", .name = "woman in manual wheelchair facing right" },
    .{ .glyph = "👩🏿‍🦽‍➡", .name = "woman in manual wheelchair facing right" },
    .{ .glyph = "🏃‍➡", .name = "person running facing right" },
    .{ .glyph = "🏃🏻‍➡", .name = "person running facing right" },
    .{ .glyph = "🏃🏼‍➡", .name = "person running facing right" },
    .{ .glyph = "🏃🏽‍➡", .name = "person running facing right" },
    .{ .glyph = "🏃🏾‍➡", .name = "person running facing right" },
    .{ .glyph = "🏃🏿‍➡", .name = "person running facing right" },
    .{ .glyph = "🏃‍♀‍➡", .name = "woman running facing right" },
    .{ .glyph = "🏃🏻‍♀‍➡", .name = "woman running facing right" },
    .{ .glyph = "🏃🏼‍♀‍➡", .name = "woman running facing right" },
    .{ .glyph = "🏃🏽‍♀‍➡", .name = "woman running facing right" },
    .{ .glyph = "🏃🏾‍♀‍➡", .name = "woman running facing right" },
    .{ .glyph = "🏃🏿‍♀‍➡", .name = "woman running facing right" },
    .{ .glyph = "🏃‍♂‍➡", .name = "man running facing right" },
    .{ .glyph = "🏃🏻‍♂‍➡", .name = "man running facing right" },
    .{ .glyph = "🏃🏼‍♂‍➡", .name = "man running facing right" },
    .{ .glyph = "🏃🏽‍♂‍➡", .name = "man running facing right" },
    .{ .glyph = "🏃🏾‍♂‍➡", .name = "man running facing right" },
    .{ .glyph = "🏃🏿‍♂‍➡", .name = "man running facing right" },
    .{ .glyph = "👩‍❤‍💋‍👨", .name = "kiss woman, man" },
    .{ .glyph = "👨‍❤‍💋‍👨", .name = "kiss man, man" },
    .{ .glyph = "👩‍❤‍💋‍👩", .name = "kiss woman, woman" },
    .{ .glyph = "👩‍❤‍👨", .name = "couple with heart woman, man" },
    .{ .glyph = "👨‍❤‍👨", .name = "couple with heart man, man" },
    .{ .glyph = "👩‍❤‍👩", .name = "couple with heart woman, woman" },
    .{ .glyph = "👨‍👩‍👦", .name = "family man, woman, boy" },
    .{ .glyph = "👨‍👩‍👧", .name = "family man, woman, girl" },
    .{ .glyph = "👨‍👩‍👧‍👦", .name = "family man, woman, girl, boy" },
    .{ .glyph = "👨‍👩‍👦‍👦", .name = "family man, woman, boy, boy" },
    .{ .glyph = "👨‍👩‍👧‍👧", .name = "family man, woman, girl, girl" },
    .{ .glyph = "👨‍👨‍👦", .name = "family man, man, boy" },
    .{ .glyph = "👨‍👨‍👧", .name = "family man, man, girl" },
    .{ .glyph = "👨‍👨‍👧‍👦", .name = "family man, man, girl, boy" },
    .{ .glyph = "👨‍👨‍👦‍👦", .name = "family man, man, boy, boy" },
    .{ .glyph = "👨‍👨‍👧‍👧", .name = "family man, man, girl, girl" },
    .{ .glyph = "👩‍👩‍👦", .name = "family woman, woman, boy" },
    .{ .glyph = "👩‍👩‍👧", .name = "family woman, woman, girl" },
    .{ .glyph = "👩‍👩‍👧‍👦", .name = "family woman, woman, girl, boy" },
    .{ .glyph = "👩‍👩‍👦‍👦", .name = "family woman, woman, boy, boy" },
    .{ .glyph = "👩‍👩‍👧‍👧", .name = "family woman, woman, girl, girl" },
    .{ .glyph = "👨‍👦", .name = "family man, boy" },
    .{ .glyph = "👨‍👦‍👦", .name = "family man, boy, boy" },
    .{ .glyph = "👨‍👧", .name = "family man, girl" },
    .{ .glyph = "👨‍👧‍👦", .name = "family man, girl, boy" },
    .{ .glyph = "👨‍👧‍👧", .name = "family man, girl, girl" },
    .{ .glyph = "👩‍👦", .name = "family woman, boy" },
    .{ .glyph = "👩‍👦‍👦", .name = "family woman, boy, boy" },
    .{ .glyph = "👩‍👧", .name = "family woman, girl" },
    .{ .glyph = "👩‍👧‍👦", .name = "family woman, girl, boy" },
    .{ .glyph = "👩‍👧‍👧", .name = "family woman, girl, girl" },
    .{ .glyph = "🔟", .name = "keycap 10" },
    .{ .glyph = "🇦🇨", .name = "flag Ascension Island" },
    .{ .glyph = "🇦🇩", .name = "flag Andorra" },
    .{ .glyph = "🇦🇪", .name = "flag United Arab Emirates" },
    .{ .glyph = "🇦🇫", .name = "flag Afghanistan" },
    .{ .glyph = "🇦🇬", .name = "flag Antigua & Barbuda" },
    .{ .glyph = "🇦🇮", .name = "flag Anguilla" },
    .{ .glyph = "🇦🇱", .name = "flag Albania" },
    .{ .glyph = "🇦🇲", .name = "flag Armenia" },
    .{ .glyph = "🇦🇴", .name = "flag Angola" },
    .{ .glyph = "🇦🇶", .name = "flag Antarctica" },
    .{ .glyph = "🇦🇷", .name = "flag Argentina" },
    .{ .glyph = "🇦🇸", .name = "flag American Samoa" },
    .{ .glyph = "🇦🇹", .name = "flag Austria" },
    .{ .glyph = "🇦🇺", .name = "flag Australia" },
    .{ .glyph = "🇦🇼", .name = "flag Aruba" },
    .{ .glyph = "🇦🇽", .name = "flag Åland Islands" },
    .{ .glyph = "🇦🇿", .name = "flag Azerbaijan" },
    .{ .glyph = "🇧🇦", .name = "flag Bosnia & Herzegovina" },
    .{ .glyph = "🇧🇧", .name = "flag Barbados" },
    .{ .glyph = "🇧🇩", .name = "flag Bangladesh" },
    .{ .glyph = "🇧🇪", .name = "flag Belgium" },
    .{ .glyph = "🇧🇫", .name = "flag Burkina Faso" },
    .{ .glyph = "🇧🇬", .name = "flag Bulgaria" },
    .{ .glyph = "🇧🇭", .name = "flag Bahrain" },
    .{ .glyph = "🇧🇮", .name = "flag Burundi" },
    .{ .glyph = "🇧🇯", .name = "flag Benin" },
    .{ .glyph = "🇧🇱", .name = "flag St. Barthélemy" },
    .{ .glyph = "🇧🇲", .name = "flag Bermuda" },
    .{ .glyph = "🇧🇳", .name = "flag Brunei" },
    .{ .glyph = "🇧🇴", .name = "flag Bolivia" },
    .{ .glyph = "🇧🇶", .name = "flag Caribbean Netherlands" },
    .{ .glyph = "🇧🇷", .name = "flag Brazil" },
    .{ .glyph = "🇧🇸", .name = "flag Bahamas" },
    .{ .glyph = "🇧🇹", .name = "flag Bhutan" },
    .{ .glyph = "🇧🇻", .name = "flag Bouvet Island" },
    .{ .glyph = "🇧🇼", .name = "flag Botswana" },
    .{ .glyph = "🇧🇾", .name = "flag Belarus" },
    .{ .glyph = "🇧🇿", .name = "flag Belize" },
    .{ .glyph = "🇨🇦", .name = "flag Canada" },
    .{ .glyph = "🇨🇨", .name = "flag Cocos (Keeling) Islands" },
    .{ .glyph = "🇨🇩", .name = "flag Congo - Kinshasa" },
    .{ .glyph = "🇨🇫", .name = "flag Central African Republic" },
    .{ .glyph = "🇨🇬", .name = "flag Congo - Brazzaville" },
    .{ .glyph = "🇨🇭", .name = "flag Switzerland" },
    .{ .glyph = "🇨🇮", .name = "flag Côte d’Ivoire" },
    .{ .glyph = "🇨🇰", .name = "flag Cook Islands" },
    .{ .glyph = "🇨🇱", .name = "flag Chile" },
    .{ .glyph = "🇨🇲", .name = "flag Cameroon" },
    .{ .glyph = "🇨🇳", .name = "flag China" },
    .{ .glyph = "🇨🇴", .name = "flag Colombia" },
    .{ .glyph = "🇨🇵", .name = "flag Clipperton Island" },
    .{ .glyph = "🇨🇷", .name = "flag Costa Rica" },
    .{ .glyph = "🇨🇺", .name = "flag Cuba" },
    .{ .glyph = "🇨🇻", .name = "flag Cape Verde" },
    .{ .glyph = "🇨🇼", .name = "flag Curaçao" },
    .{ .glyph = "🇨🇽", .name = "flag Christmas Island" },
    .{ .glyph = "🇨🇾", .name = "flag Cyprus" },
    .{ .glyph = "🇨🇿", .name = "flag Czechia" },
    .{ .glyph = "🇩🇪", .name = "flag Germany" },
    .{ .glyph = "🇩🇬", .name = "flag Diego Garcia" },
    .{ .glyph = "🇩🇯", .name = "flag Djibouti" },
    .{ .glyph = "🇩🇰", .name = "flag Denmark" },
    .{ .glyph = "🇩🇲", .name = "flag Dominica" },
    .{ .glyph = "🇩🇴", .name = "flag Dominican Republic" },
    .{ .glyph = "🇩🇿", .name = "flag Algeria" },
    .{ .glyph = "🇪🇦", .name = "flag Ceuta & Melilla" },
    .{ .glyph = "🇪🇨", .name = "flag Ecuador" },
    .{ .glyph = "🇪🇪", .name = "flag Estonia" },
    .{ .glyph = "🇪🇬", .name = "flag Egypt" },
    .{ .glyph = "🇪🇭", .name = "flag Western Sahara" },
    .{ .glyph = "🇪🇷", .name = "flag Eritrea" },
    .{ .glyph = "🇪🇸", .name = "flag Spain" },
    .{ .glyph = "🇪🇹", .name = "flag Ethiopia" },
    .{ .glyph = "🇪🇺", .name = "flag European Union" },
    .{ .glyph = "🇫🇮", .name = "flag Finland" },
    .{ .glyph = "🇫🇯", .name = "flag Fiji" },
    .{ .glyph = "🇫🇰", .name = "flag Falkland Islands" },
    .{ .glyph = "🇫🇲", .name = "flag Micronesia" },
    .{ .glyph = "🇫🇴", .name = "flag Faroe Islands" },
    .{ .glyph = "🇫🇷", .name = "flag France" },
    .{ .glyph = "🇬🇦", .name = "flag Gabon" },
    .{ .glyph = "🇬🇧", .name = "flag United Kingdom" },
    .{ .glyph = "🇬🇩", .name = "flag Grenada" },
    .{ .glyph = "🇬🇪", .name = "flag Georgia" },
    .{ .glyph = "🇬🇫", .name = "flag French Guiana" },
    .{ .glyph = "🇬🇬", .name = "flag Guernsey" },
    .{ .glyph = "🇬🇭", .name = "flag Ghana" },
    .{ .glyph = "🇬🇮", .name = "flag Gibraltar" },
    .{ .glyph = "🇬🇱", .name = "flag Greenland" },
    .{ .glyph = "🇬🇲", .name = "flag Gambia" },
    .{ .glyph = "🇬🇳", .name = "flag Guinea" },
    .{ .glyph = "🇬🇵", .name = "flag Guadeloupe" },
    .{ .glyph = "🇬🇶", .name = "flag Equatorial Guinea" },
    .{ .glyph = "🇬🇷", .name = "flag Greece" },
    .{ .glyph = "🇬🇸", .name = "flag South Georgia & South Sandwich Islands" },
    .{ .glyph = "🇬🇹", .name = "flag Guatemala" },
    .{ .glyph = "🇬🇺", .name = "flag Guam" },
    .{ .glyph = "🇬🇼", .name = "flag Guinea-Bissau" },
    .{ .glyph = "🇬🇾", .name = "flag Guyana" },
    .{ .glyph = "🇭🇰", .name = "flag Hong Kong SAR China" },
    .{ .glyph = "🇭🇲", .name = "flag Heard & McDonald Islands" },
    .{ .glyph = "🇭🇳", .name = "flag Honduras" },
    .{ .glyph = "🇭🇷", .name = "flag Croatia" },
    .{ .glyph = "🇭🇹", .name = "flag Haiti" },
    .{ .glyph = "🇭🇺", .name = "flag Hungary" },
    .{ .glyph = "🇮🇨", .name = "flag Canary Islands" },
    .{ .glyph = "🇮🇩", .name = "flag Indonesia" },
    .{ .glyph = "🇮🇪", .name = "flag Ireland" },
    .{ .glyph = "🇮🇱", .name = "flag Israel" },
    .{ .glyph = "🇮🇲", .name = "flag Isle of Man" },
    .{ .glyph = "🇮🇳", .name = "flag India" },
    .{ .glyph = "🇮🇴", .name = "flag British Indian Ocean Territory" },
    .{ .glyph = "🇮🇶", .name = "flag Iraq" },
    .{ .glyph = "🇮🇷", .name = "flag Iran" },
    .{ .glyph = "🇮🇸", .name = "flag Iceland" },
    .{ .glyph = "🇮🇹", .name = "flag Italy" },
    .{ .glyph = "🇯🇪", .name = "flag Jersey" },
    .{ .glyph = "🇯🇲", .name = "flag Jamaica" },
    .{ .glyph = "🇯🇴", .name = "flag Jordan" },
    .{ .glyph = "🇯🇵", .name = "flag Japan" },
    .{ .glyph = "🇰🇪", .name = "flag Kenya" },
    .{ .glyph = "🇰🇬", .name = "flag Kyrgyzstan" },
    .{ .glyph = "🇰🇭", .name = "flag Cambodia" },
    .{ .glyph = "🇰🇮", .name = "flag Kiribati" },
    .{ .glyph = "🇰🇲", .name = "flag Comoros" },
    .{ .glyph = "🇰🇳", .name = "flag St. Kitts & Nevis" },
    .{ .glyph = "🇰🇵", .name = "flag North Korea" },
    .{ .glyph = "🇰🇷", .name = "flag South Korea" },
    .{ .glyph = "🇰🇼", .name = "flag Kuwait" },
    .{ .glyph = "🇰🇾", .name = "flag Cayman Islands" },
    .{ .glyph = "🇰🇿", .name = "flag Kazakhstan" },
    .{ .glyph = "🇱🇦", .name = "flag Laos" },
    .{ .glyph = "🇱🇧", .name = "flag Lebanon" },
    .{ .glyph = "🇱🇨", .name = "flag St. Lucia" },
    .{ .glyph = "🇱🇮", .name = "flag Liechtenstein" },
    .{ .glyph = "🇱🇰", .name = "flag Sri Lanka" },
    .{ .glyph = "🇱🇷", .name = "flag Liberia" },
    .{ .glyph = "🇱🇸", .name = "flag Lesotho" },
    .{ .glyph = "🇱🇹", .name = "flag Lithuania" },
    .{ .glyph = "🇱🇺", .name = "flag Luxembourg" },
    .{ .glyph = "🇱🇻", .name = "flag Latvia" },
    .{ .glyph = "🇱🇾", .name = "flag Libya" },
    .{ .glyph = "🇲🇦", .name = "flag Morocco" },
    .{ .glyph = "🇲🇨", .name = "flag Monaco" },
    .{ .glyph = "🇲🇩", .name = "flag Moldova" },
    .{ .glyph = "🇲🇪", .name = "flag Montenegro" },
    .{ .glyph = "🇲🇫", .name = "flag St. Martin" },
    .{ .glyph = "🇲🇬", .name = "flag Madagascar" },
    .{ .glyph = "🇲🇭", .name = "flag Marshall Islands" },
    .{ .glyph = "🇲🇰", .name = "flag North Macedonia" },
    .{ .glyph = "🇲🇱", .name = "flag Mali" },
    .{ .glyph = "🇲🇲", .name = "flag Myanmar (Burma)" },
    .{ .glyph = "🇲🇳", .name = "flag Mongolia" },
    .{ .glyph = "🇲🇴", .name = "flag Macao SAR China" },
    .{ .glyph = "🇲🇵", .name = "flag Northern Mariana Islands" },
    .{ .glyph = "🇲🇶", .name = "flag Martinique" },
    .{ .glyph = "🇲🇷", .name = "flag Mauritania" },
    .{ .glyph = "🇲🇸", .name = "flag Montserrat" },
    .{ .glyph = "🇲🇹", .name = "flag Malta" },
    .{ .glyph = "🇲🇺", .name = "flag Mauritius" },
    .{ .glyph = "🇲🇻", .name = "flag Maldives" },
    .{ .glyph = "🇲🇼", .name = "flag Malawi" },
    .{ .glyph = "🇲🇽", .name = "flag Mexico" },
    .{ .glyph = "🇲🇾", .name = "flag Malaysia" },
    .{ .glyph = "🇲🇿", .name = "flag Mozambique" },
    .{ .glyph = "🇳🇦", .name = "flag Namibia" },
    .{ .glyph = "🇳🇨", .name = "flag New Caledonia" },
    .{ .glyph = "🇳🇪", .name = "flag Niger" },
    .{ .glyph = "🇳🇫", .name = "flag Norfolk Island" },
    .{ .glyph = "🇳🇬", .name = "flag Nigeria" },
    .{ .glyph = "🇳🇮", .name = "flag Nicaragua" },
    .{ .glyph = "🇳🇱", .name = "flag Netherlands" },
    .{ .glyph = "🇳🇴", .name = "flag Norway" },
    .{ .glyph = "🇳🇵", .name = "flag Nepal" },
    .{ .glyph = "🇳🇷", .name = "flag Nauru" },
    .{ .glyph = "🇳🇺", .name = "flag Niue" },
    .{ .glyph = "🇳🇿", .name = "flag New Zealand" },
    .{ .glyph = "🇴🇲", .name = "flag Oman" },
    .{ .glyph = "🇵🇦", .name = "flag Panama" },
    .{ .glyph = "🇵🇪", .name = "flag Peru" },
    .{ .glyph = "🇵🇫", .name = "flag French Polynesia" },
    .{ .glyph = "🇵🇬", .name = "flag Papua New Guinea" },
    .{ .glyph = "🇵🇭", .name = "flag Philippines" },
    .{ .glyph = "🇵🇰", .name = "flag Pakistan" },
    .{ .glyph = "🇵🇱", .name = "flag Poland" },
    .{ .glyph = "🇵🇲", .name = "flag St. Pierre & Miquelon" },
    .{ .glyph = "🇵🇳", .name = "flag Pitcairn Islands" },
    .{ .glyph = "🇵🇷", .name = "flag Puerto Rico" },
    .{ .glyph = "🇵🇸", .name = "flag Palestinian Territories" },
    .{ .glyph = "🇵🇹", .name = "flag Portugal" },
    .{ .glyph = "🇵🇼", .name = "flag Palau" },
    .{ .glyph = "🇵🇾", .name = "flag Paraguay" },
    .{ .glyph = "🇶🇦", .name = "flag Qatar" },
    .{ .glyph = "🇷🇪", .name = "flag Réunion" },
    .{ .glyph = "🇷🇴", .name = "flag Romania" },
    .{ .glyph = "🇷🇸", .name = "flag Serbia" },
    .{ .glyph = "🇷🇺", .name = "flag Russia" },
    .{ .glyph = "🇷🇼", .name = "flag Rwanda" },
    .{ .glyph = "🇸🇦", .name = "flag Saudi Arabia" },
    .{ .glyph = "🇸🇧", .name = "flag Solomon Islands" },
    .{ .glyph = "🇸🇨", .name = "flag Seychelles" },
    .{ .glyph = "🇸🇩", .name = "flag Sudan" },
    .{ .glyph = "🇸🇪", .name = "flag Sweden" },
    .{ .glyph = "🇸🇬", .name = "flag Singapore" },
    .{ .glyph = "🇸🇭", .name = "flag St. Helena" },
    .{ .glyph = "🇸🇮", .name = "flag Slovenia" },
    .{ .glyph = "🇸🇯", .name = "flag Svalbard & Jan Mayen" },
    .{ .glyph = "🇸🇰", .name = "flag Slovakia" },
    .{ .glyph = "🇸🇱", .name = "flag Sierra Leone" },
    .{ .glyph = "🇸🇲", .name = "flag San Marino" },
    .{ .glyph = "🇸🇳", .name = "flag Senegal" },
    .{ .glyph = "🇸🇴", .name = "flag Somalia" },
    .{ .glyph = "🇸🇷", .name = "flag Suriname" },
    .{ .glyph = "🇸🇸", .name = "flag South Sudan" },
    .{ .glyph = "🇸🇹", .name = "flag São Tomé & Príncipe" },
    .{ .glyph = "🇸🇻", .name = "flag El Salvador" },
    .{ .glyph = "🇸🇽", .name = "flag Sint Maarten" },
    .{ .glyph = "🇸🇾", .name = "flag Syria" },
    .{ .glyph = "🇸🇿", .name = "flag Eswatini" },
    .{ .glyph = "🇹🇦", .name = "flag Tristan da Cunha" },
    .{ .glyph = "🇹🇨", .name = "flag Turks & Caicos Islands" },
    .{ .glyph = "🇹🇩", .name = "flag Chad" },
    .{ .glyph = "🇹🇫", .name = "flag French Southern Territories" },
    .{ .glyph = "🇹🇬", .name = "flag Togo" },
    .{ .glyph = "🇹🇭", .name = "flag Thailand" },
    .{ .glyph = "🇹🇯", .name = "flag Tajikistan" },
    .{ .glyph = "🇹🇰", .name = "flag Tokelau" },
    .{ .glyph = "🇹🇱", .name = "flag Timor-Leste" },
    .{ .glyph = "🇹🇲", .name = "flag Turkmenistan" },
    .{ .glyph = "🇹🇳", .name = "flag Tunisia" },
    .{ .glyph = "🇹🇴", .name = "flag Tonga" },
    .{ .glyph = "🇹🇷", .name = "flag Türkiye" },
    .{ .glyph = "🇹🇹", .name = "flag Trinidad & Tobago" },
    .{ .glyph = "🇹🇻", .name = "flag Tuvalu" },
    .{ .glyph = "🇹🇼", .name = "flag Taiwan" },
    .{ .glyph = "🇹🇿", .name = "flag Tanzania" },
    .{ .glyph = "🇺🇦", .name = "flag Ukraine" },
    .{ .glyph = "🇺🇬", .name = "flag Uganda" },
    .{ .glyph = "🇺🇲", .name = "flag U.S. Outlying Islands" },
    .{ .glyph = "🇺🇳", .name = "flag United Nations" },
    .{ .glyph = "🇺🇸", .name = "flag United States" },
    .{ .glyph = "🇺🇾", .name = "flag Uruguay" },
    .{ .glyph = "🇺🇿", .name = "flag Uzbekistan" },
    .{ .glyph = "🇻🇦", .name = "flag Vatican City" },
    .{ .glyph = "🇻🇨", .name = "flag St. Vincent & Grenadines" },
    .{ .glyph = "🇻🇪", .name = "flag Venezuela" },
    .{ .glyph = "🇻🇬", .name = "flag British Virgin Islands" },
    .{ .glyph = "🇻🇮", .name = "flag U.S. Virgin Islands" },
    .{ .glyph = "🇻🇳", .name = "flag Vietnam" },
    .{ .glyph = "🇻🇺", .name = "flag Vanuatu" },
    .{ .glyph = "🇼🇫", .name = "flag Wallis & Futuna" },
    .{ .glyph = "🇼🇸", .name = "flag Samoa" },
    .{ .glyph = "🇽🇰", .name = "flag Kosovo" },
    .{ .glyph = "🇾🇪", .name = "flag Yemen" },
    .{ .glyph = "🇾🇹", .name = "flag Mayotte" },
    .{ .glyph = "🇿🇦", .name = "flag South Africa" },
    .{ .glyph = "🇿🇲", .name = "flag Zambia" },
    .{ .glyph = "🇿🇼", .name = "flag Zimbabwe" },
    .{ .glyph = "🏴󠁧󠁢󠁥󠁮󠁧󠁿", .name = "flag England" },
    .{ .glyph = "🏴󠁧󠁢󠁳󠁣󠁴󠁿", .name = "flag Scotland" },
    .{ .glyph = "🏴󠁧󠁢󠁷󠁬󠁳󠁿", .name = "flag Wales" },
};
